### ISSUE TITLE
[BUG]抖音小播间加载大半天才出来

### ISSUE THREAD

**Issue by yaohuo365** [xiaoyaocz/dart_simple_live#115]
![Screenshot_2023-08-24-17-11-42-156_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/130054234/dacfd02e-017f-4c93-9251-25ba6d6ea3a2)
加载不出来，或者要大半天

**Comment by xiaoyaocz** [comment]
无法解决此问题，视频链接都是从抖音网页版读取的，可能CDN链接并没有预热导致加载过慢。
可以尝试更换清晰度、线路

**Comment by yaohuo365** [comment]
好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月30日 16:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xiaoyaocz/dart_simple_live] [BUG]抖音小播间加载大半天才出来 (Issue #115) |

无法解决此问题，视频链接都是从抖音网页版读取的，可能CDN链接并没有预热导致加载过慢。
可以尝试更换清晰度、线路
