### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by carlo0505** [xiaoyaocz/dart_simple_live#119]
虎牙直播：后台播放功能虽然已经有了，但是息屏之后播放十分钟左右就会自动切换其他线路断开连接，希望大大可以改进一下这个问题，需要灭屏听直播的时候就不太好用了

![微信截图_20230828204138](https://github.com/xiaoyaocz/dart_simple_live/assets/87769666/556a6807-83f1-4831-a11d-9870412b7f0d)

**Comment by xiaoyaocz** [comment]
#13
