### ISSUE TITLE
[BUG]抖音直播无法观看

### ISSUE THREAD

**Issue by inoyna12** [xiaoyaocz/dart_simple_live#121]
导航栏都加载不出来了![Screenshot_2023-09-04-23-35-17-299_com.xycz.simple_live.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/86736950/77fa2e80-41a2-4b14-a592-eebd61310ae0)

**Comment by kristin0512** [comment]
俺也一样

**Comment by clarkee1** [comment]
我也一样

**Comment by anjinga** [comment]
俺也打不开，期待作者的更新修复，感谢

**Comment by inoyna12** [comment]
又不能看了

**Comment by kkikikikii** [comment]
不能看了

**Comment by dongbao66** [comment]
![Screenshot_2023-09-13-01-24-33-66_e3cd25cd7d1683da6f376a9c501d0866](https://github.com/xiaoyaocz/dart_simple_live/assets/95880227/8c9af78e-308c-4218-a19e-11eea052f7c1)
抖音无法观看
