### ISSUE TITLE
[BUG] 1.3.0虎牙直播间进入概率黑屏。

### ISSUE THREAD

**Issue by withered233** [xiaoyaocz/dart_simple_live#125]
1.3.0版本 进入虎牙直播间大概率显示黑屏但有声音，刷新后正常。
![S30907-13595920_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/60478611/b01a464c-1044-47b3-9fb3-86e15050c84b)

**Comment by xiaoyaocz** [comment]
无法复现，尝试打开播放设置里的"兼容模式"

**Comment by withered233** [comment]
> 无法复现，尝试打开播放设置里的"兼容模式"

兼容模式一直开启的，录了个视频。
[复现视频](https://easylink.cc/rpaoo7)

**Comment by xiaoyaocz** [comment]
把"兼容模式"关掉看看

**Comment by withered233** [comment]
> 把"兼容模式"关掉看看

关掉 兼容模式 后也是会复现。

**Comment by anjinga** [comment]
我也会出现这种情况，部分虎牙直播间打开是黑屏但有声音，其他平台没有问题

**Comment by ShimaRain** [comment]
android有这种情况，iOS没有

**Comment by xiaoyaocz** [comment]
大概是视频解码问题，看下怎么解决

**Comment by withered233** [comment]
> 大概是视频解码问题，看下怎么解决

退回1.2.4就好了😁

**Comment by yangzhe69** [comment]
+1 开始是退了重新进 后面直接重新刷新一下也可以

**Comment by inoyna12** [comment]
+1

**Comment by xiaoyaocz** [comment]
尝试修复了下，可以试试这个版本看还会不会出现黑屏
https://xiaoyaocz.lanzouy.com/itumq18crl1g

PS:未开启“兼容模式”时会有几秒的黑屏加载

**Comment by withered233** [comment]
> 尝试修复了下，可以试试这个版本看还会不会出现黑屏 https://xiaoyaocz.lanzouy.com/itumq18crl1g
> 
> PS:未开启“兼容模式”时会有几秒的黑屏加载

试下来几十次没有复现，修好了应该😁
