### ISSUE TITLE
尝试在linux运行。请问播放页按钮文本的样式在哪里改？似乎不受主题控制

### ISSUE THREAD

**Issue by kero990** [xiaoyaocz/dart_simple_live#131]
橙子大大您好，您的app现在是我手机、ipad上的主力直播软件（坐等tv适配）
现在我心血来潮用flutter create .  创建了linux文件夹，居然能用。
不过我现在在用deepin，flutter的默认字体无法识别，必须自己适配。
我尝试在/lib/app/app_style.dart中的两个theme里添加了fontFamily: 'Noto Sans CJK SC',现在大部分中文都正常了

但播放页的外框文本还是口口，包括直播间名称，下面的刷新收藏分享按钮。我对flutter了解有限，不知道这俩不在主题里的文本样式在哪里改。
打扰了，如有时间，请赐教。

**Comment by xiaoyaocz** [comment]
找到对应的TextStyle，设置`fontFamily`
以及桌面代码可以切换至desktop分组
