### ISSUE TITLE
虎牙和抖音直播间播放画面黑屏

### ISSUE THREAD

**Issue by zhusuner** [xiaoyaocz/dart_simple_live#134]
**BUG内容**
·发现虎牙和抖音线路一播放黑屏只有声音。这些问题线路后缀都是flv，hls是正常的。
·经反复使用又发现这个bug在刚进入直播间黑屏只有声音，然后多次点击刷新按钮，就可以恢复正常。具体如图所示
**重现步骤**
请在此输入重现步骤
搜索直播间，即可重现。几个典型直播间具体如下
：搜索抖音直播间→东方甄选→ 
 https://live.douyin.com/80017709309
    虎牙直播间→https://www.huya.com/100
（或者去平台专区进入任意直播间即可，但是有的可以重现bug有的不行）

**截图或视频**
![Screenshot_20230913_185529](https://github.com/xiaoyaocz/dart_simple_live/assets/80241679/aa3d51dd-d8bd-4b2e-b2c5-82fb226355aa)
2

**平台信息**
 - 设备: vivo x90
 - 系统版本: 安卓13
 - app版本:1.3.1（action最新版）

**Comment by xiaoyaocz** [comment]
合并 #125
