### ISSUE TITLE
[Feature]桌面版换个图标

### ISSUE THREAD

**Issue by tttzzzzz** [xiaoyaocz/dart_simple_live#140]
**类型**
- 新功能
- 功能优化
- 新平台

**描述**
输入具体的功能描述
反馈前请确认下是否存在相似的Issues！！！

**附加**
请附加相关截图、视频或链接

**Comment by xiaoyaocz** [comment]
图标原图丢失了，桌面版只能随便找个图标用用了😂
桌面平台到正式发布时再换了

**Comment by LOVEgithub12** [comment]
我自己ps的图标 
预览：http://mrw.so/6gAxDu
下载：http://mrw.so/5UIhSX
