### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by long1512448773** [xiaoyaocz/dart_simple_live#143]
**类型**登入账号
- 新功能 可以设置一个每个不同的平台登入账号入口
- 功能优化登入功能
- 新平台

**描述*
可以在设置里面增加一个切换账号登入不同平台的入口这样就可以看关注列表里面的内容啦！

**附加**
请附加相关截图、视频或链接

**Comment by xiaoyaocz** [comment]
不会开发登录功能，除非直播必须要登录才能看
