### ISSUE TITLE
[BUG]虎牙一起看打开播放大概四五分钟后会自动暂停，手动刷新后课正常播放，但再播放个几分钟后仍会自动暂停

### ISSUE THREAD

**Issue by wyy0814** [xiaoyaocz/dart_simple_live#144]
**BUG内容**
输入BUG详细内容
反馈前请确认下是否存在相似的Issues！！！

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**
在这里贴上截图或视频

**平台信息**
 - 设备: [e.g. iPhone6]
 - 系统版本: [e.g. iOS 15, Android 10.0]
 - APP版本: [e.g. 22]

**Comment by xiaoyaocz** [comment]
合并#86 ，暂时无法解决
