### ISSUE TITLE
[BUG]虎牙直播  只有声音没有画面

### ISSUE THREAD

**Issue by dongbao66** [xiaoyaocz/dart_simple_live#145]
**BUG内容**
输入BUG详细内容
反馈前请确认下是否存在相似的Issues！！！

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**
在这里贴上截图或视频

**平台信息**
 - 设备: [e.g. iPhone6]
 - 系统版本: [e.g. iOS 15, Android 10.0]
 - APP版本: 最新版本

**Comment by xiaoyaocz** [comment]
合并 #125

**Comment by dongbao66** [comment]
还真是刷新后 解决
