### ISSUE TITLE
[Feature] 支持智能电视

### ISSUE THREAD

**Issue by ArsenicX** [xiaoyaocz/dart_simple_live#15]
感谢大佬的开发，现在在电视上不能按确定，如果能支持一下智能电视就更好了。

**Comment by zhdsmy** [comment]
大佬也考虑一下 AppleTV，100% 支持 App 付费

**Comment by Oosl** [comment]
臣复议🙉添加遥控按键的支持赛高

**Comment by sandaisi** [comment]
强烈建议支持TV端，那就完美了

**Comment by RyanForJU** [comment]
希望支持智能电视

**Comment by Firehacher** [comment]
希望大佬支持tv端

**Comment by xiaoyaocz** [comment]
Apple TV可关注此项目：https://github.com/pcccccc/SimpleLiveTVOS

**Comment by eason27** [comment]
Android TV的还能有吗

**Comment by rudolfchen** [comment]
> 感谢大佬的开发，现在在电视上不能按确定，如果能支持一下智能电视就更好了。

请问各位老哥，这3个版本，哪个可以安装在机顶盒上？
app-arm64-v8a-release.apk
app-armeabi-v7a-release.apk
app-x86_64-release.apk
安卓的版本是否有要求？ 
谢谢

**Comment by 1010247556** [comment]
安卓TV遥控器确定键无效

**Comment by wangxingxing11** [comment]
希望支持TV端

**Comment by szl2733** [comment]
安卓 Tv 按确定无效

**Comment by xiaoyaocz** [comment]
可前往 #338 下载TV端
