### ISSUE TITLE
[BUG]观看b站直播一段时间，弹幕用户名称边星号**

### ISSUE THREAD

**Issue by dongbao66** [xiaoyaocz/dart_simple_live#150]
![Uploading Screenshot_2023-09-21-15-07-34-31_e3cd25cd7d1683da6f376a9c501d0866.jpg…]()

**Comment by dongbao66** [comment]
![Screenshot_2023-09-21-15-07-34-31_e3cd25cd7d1683da6f376a9c501d0866](https://github.com/xiaoyaocz/dart_simple_live/assets/95880227/4c97670c-5536-425c-a68d-f04ebae42130)

**Comment by xiaoyaocz** [comment]
应该是阿B需要登录才能显示用户名了

**Comment by dongbao66** [comment]
> 应该是阿B需要登录才能显示用户名了

那还能修复不
