### ISSUE TITLE
[Feature]能不能发布个tf版的，签名太麻烦了

### ISSUE THREAD

**Issue by lewpc1996** [xiaoyaocz/dart_simple_live#170]
**类型**
- 新功能
- 功能优化
- 新平台

**描述**
输入具体的功能描述
反馈前请确认下是否存在相似的Issues！！！

**附加**
请附加相关截图、视频或链接

**Comment by xiaoyaocz** [comment]
不能。
1. 没有开发者账号
2. 大概率无法通过苹果审核
