### ISSUE TITLE
[BUG] ios端以及android设备均出现单击屏幕无法调出功能，只能调节音量的bug

### ISSUE THREAD

**Issue by mis-u** [xiaoyaocz/dart_simple_live#171]
**BUG内容**
输入BUG详细内容
反馈前请确认下是否存在相似的Issues！！！

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**
在这里贴上截图或视频

**平台信息**
 - 设备: [e.g. iPhone6]
 - 系统版本: [e.g. iOS 15, Android 10.0]
 - APP版本: [e.g. 22]

**Comment by xiaoyaocz** [comment]
合并 #168
