### ISSUE TITLE
[BUG] Windows直播画面出现闪屏现象

### ISSUE THREAD

**Issue by SoYoungHa** [xiaoyaocz/dart_simple_live#173]
**直播画面出现闪屏现象**
疑似在看斗鱼平台一些主播的画质选项有2K60的时候会出现这种情况

**截图或视频**

**平台信息**
 - 设备: [PC]
 - 系统版本: [windows10 21H2]

https://github.com/xiaoyaocz/dart_simple_live/assets/69039119/a7792e01-07d9-47b7-a549-fc7f424b29f5

 - APP版本: [1.4.1]

Uploading freecompress-Simple-Live-2023-10-08-16-43-52.mp4…

**Comment by loveproe** [comment]
没错，确认重复出现，以前版本没有。

**Comment by xiaoyaocz** [comment]
我这边无法复现。是只在Windows出现吗？

**Comment by SoYoungHa** [comment]
> 我这边无法复现。是只在Windows出现吗？

目前看来是的，手机没事

**Comment by xiaoyaocz** [comment]
1.4.0的版本是否会出现此问题？

**Comment by SoYoungHa** [comment]
> 1.4.0的版本是否会出现此问题？

两个版本都碰到过，但是在我工位的电脑没复现这种情况 win11 22H2，1.4.1
