### ISSUE TITLE
[BUG]导出文件异常

### ISSUE THREAD

**Issue by yuf19-2022** [xiaoyaocz/dart_simple_live#177]
**BUG内容**
输入BUG详细内容
反馈前请确认下是否存在相似的Issues！！！

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**
![Screenshot_20231008_220121.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/109777030/6c97703c-4c24-414e-9c22-b02cf4b68bff)

![Screenshot_2023_1008_220142.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/109777030/3c6e868b-6f8c-4c2f-b3ac-3aa75197d961)

![Screenshot_20231008_215626.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/109777030/5d657ec3-317f-49c0-93ed-ec3c6c0b188d)

在这里贴上截图或视频

**平台信息**
 - 设备: [e.g. iPhone6]
 - 系统版本: [e.g. iOS 15, Android 10.0]
 - APP版本: [e.g. 22]

**Comment by xiaoyaocz** [comment]
合并 #100
