### ISSUE TITLE
[Feature]急需ios的后台播放和小窗播放功能，退出软件就暂停播放太影响使用了

### ISSUE THREAD

**Issue by lewpc1996** [xiaoyaocz/dart_simple_live#179]
**类型**
- 新功能
- 功能优化
- 新平台

**描述**
输入具体的功能描述
反馈前请确认下是否存在相似的Issues！！！

**附加**
请附加相关截图、视频或链接

**Comment by xiaoyaocz** [comment]
iOS画中画需要上游播放器组件（media_kit）支持，暂时无法解决

**Comment by xiaoyaocz** [comment]
重复#165
