### ISSUE TITLE
[BUG] 虎牙部分直播间会自动断开

### ISSUE THREAD

**Issue by mis-u** [xiaoyaocz/dart_simple_live#185]
**BUG内容**
输入BUG详细内容
反馈前请确认下是否存在相似的Issues！！！

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**
在这里贴上截图或视频
<img width="949" alt="1" src="https://github.com/xiaoyaocz/dart_simple_live/assets/147301877/695868f7-8d2b-4ee2-a1e4-33f50486c00b">
<img width="941" alt="2" src="https://github.com/xiaoyaocz/dart_simple_live/assets/147301877/2f631955-da06-4eb2-8602-50b24e9d4297">

**平台信息**
 - 设备: [e.g. iPhone6]
 - 系统版本: [e.g. iOS 15, Android 10.0]
 - APP版本: [e.g. 22]

**Comment by mis-u** [comment]
win10 22h2  还会出现很长的报错类似于不能从simple live播放这样
手机是一加ace2 手机貌似概率小一点

**Comment by xiaoyaocz** [comment]
应该是只有虎牙部分直播间会这样，大概观看两分钟会自动断开

**Comment by mis-u** [comment]
> 应该是只有虎牙部分直播间会这样，大概观看两分钟会自动断开

不知道  看虎牙比较多 其他几乎不怎么看

**Comment by pcccccc** [comment]
今天大概看了一下，希望可以帮到你。

我在虎牙解析参考了一个real-url的fork：

[https://github.com/iceking2nd/real-url](real-url)

看到这个问题以后我就同时获取了m3u8和flv两种格式的源，同时使用iina播放，发现m3u8确实是会在两分钟左右断开而flv播放了十分钟依然正常。

如果你目前使用m3u8地址的话直接切换到flv应该就可以解决这个问题了。

**Comment by xiaoyaocz** [comment]
> 今天大概看了一下，希望可以帮到你。
> 
> 我在虎牙解析参考了一个real-url的fork：
> 
> [https://github.com/iceking2nd/real-url](real-url)
> 
> 看到这个问题以后我就同时获取了m3u8和flv两种格式的源，同时使用iina播放，发现m3u8确实是会在两分钟左右断开而flv播放了十分钟依然正常。
> 
> 如果你目前使用m3u8地址的话直接切换到flv应该就可以解决这个问题了。

已修复 5d42cfc。修改以下两个参数就行了
```
query["t"] = "100";
query["ctype"] = "huya_live";
```

**Comment by mis-u** [comment]
> > 今天大概看了一下，希望可以帮到你。
> > 我在虎牙解析参考了一个real-url的fork：
> > [https://github.com/iceking2nd/real-url](real-url)
> > 看到这个问题以后我就同时获取了m3u8和flv两种格式的源，同时使用iina播放，发现m3u8确实是会在两分钟左右断开而flv播放了十分钟依然正常。
> > 如果你目前使用m3u8地址的话直接切换到flv应该就可以解决这个问题了。
> 
> 已修复 [5d42cfc](https://github.com/xiaoyaocz/dart_simple_live/commit/5d42cfcc003f61c41baa58c81a93fe532d7d9bf7)。修改以下两个参数就行了
> 
> ```
> query["t"] = "100";
> query["ctype"] = "huya_live";
> ```

   好的  谢谢  但是我能说不知道怎么改吗

**Comment by xiaoyaocz** [comment]
这是代码的改动。等下个版本更新就行了。

**Comment by mis-u** [comment]
> 这是代码的改动。等下个版本更新就行了。

  好的   麻烦了

**Comment by pcccccc** [comment]
> > 今天大概看了一下，希望可以帮到你。
> > 我在虎牙解析参考了一个real-url的fork：
> > [https://github.com/iceking2nd/real-url](real-url)
> > 看到这个问题以后我就同时获取了m3u8和flv两种格式的源，同时使用iina播放，发现m3u8确实是会在两分钟左右断开而flv播放了十分钟依然正常。
> > 如果你目前使用m3u8地址的话直接切换到flv应该就可以解决这个问题了。
> 
> 已修复 [5d42cfc](https://github.com/xiaoyaocz/dart_simple_live/commit/5d42cfcc003f61c41baa58c81a93fe532d7d9bf7)。修改以下两个参数就行了
> 
> ```
> query["t"] = "100";
> query["ctype"] = "huya_live";
> ```

好的，我看下，如果这种改起来比较简单我也改一下。

**Comment by mis-u** [comment]
> 这是代码的改动。等下个版本更新就行了。

![Screenshot_2023-10-14-16-18-34-54_e3cd25cd7d1683d](https://github.com/xiaoyaocz/dart_simple_live/assets/147301877/9e78134e-e477-4b61-a719-3e2df456f9a9)
安卓设备会这样  这应该是flv吧？

**Comment by mis-u** [comment]
> 这是代码的改动。等下个版本更新就行了。

画面静止不动 卡住了

**Comment by mis-u** [comment]
> > 这是代码的改动。等下个版本更新就行了。
> 
> 好的 麻烦了

而且今天发现windows端貌似会闪屏
