### ISSUE TITLE
simple live相比于聚合直播GPU占用太高

### ISSUE THREAD

**Issue by TakotsuboChen** [xiaoyaocz/dart_simple_live#187]
设备是Windows平板Surface Pro 6
i5-8250U
UHD 620核显

同样看一个直播间的蓝光4M，simple live平均功耗高达12.5W，聚合直播只有4W左右，查看占用情况，前者CPU占用22%，GPU占用高达80%，而后者分别为16%和20%。

轻薄Windows设备使用simple live会有较为严重的发热情况，希望可以优化一下。

**Comment by xiaoyaocz** [comment]
Flutter程序运行效率肯定没有原生UWP效率高的。轻薄设备还是建议用UWP。
