### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BLACKGODSERVER** [xiaoyaocz/dart_simple_live#189]
**BUG内容**
抖音专栏的所有直播和功能无法使用

**截图或视频**
![image](https://github.com/xiaoyaocz/dart_simple_live/assets/100487092/ba0286b4-6761-472e-9631-7a2a40e63222)

**平台信息**
 - 设备: [iPad Air 4 WLAN]
 - 系统版本: [iOS 16.2]
 - APP版本: [1.4.1]

**Comment by BLACKGODSERVER** [comment]
bili 斗鱼 虎牙 正常！

**Comment by xiaoyaocz** [comment]
请求频繁被抖音限制了，可尝试：
- 过段时间再试
- 换个网络环境

**Comment by BLACKGODSERVER** [comment]
建议开一个可以同时看多个直播的功能
