### ISSUE TITLE
[Feature] 一个请求

### ISSUE THREAD

**Issue by Lee-Asuka** [xiaoyaocz/dart_simple_live#193]
软件好用方便。虽然作为一个使用者仍要提出要求有点过分，但还是希望能有后台播放的功能。
如果给你带来了麻烦和困扰，请无视此请求
设备：iPhone11 pro max

**Comment by xiaoyaocz** [comment]
iOS后台、画中画需要上游播放器组件（media_kit）支持，暂时无法解决
合并 #13
