### ISSUE TITLE
[BUG] B站直播画质有误

### ISSUE THREAD

**Issue by CharWhyChar** [xiaoyaocz/dart_simple_live#209]
**BUG内容**
B站目前直播似乎无论如何切换画质都会以较低画质直播，切换线路也无法改变画质。
另外现在如果在浏览历史弹幕的时候出现新弹幕，会直接跳屏到最新一行，希望加入弹幕自动锁定功能，滑屏查看历史弹幕的时候锁定弹幕不要跳到最新一行，然后弹出解除锁定按键，触发自动跳回最新一行（也就是正常的弹幕浏览功能）。

**Comment by Icecream-2018** [comment]
感觉是权限被限制了，默认360p画质，可以考虑试试出个绑定个人账户的功能。

**Comment by thouser8** [comment]
B站改了东西，另一个项目出现了同样的问题

**Comment by xiaoyaocz** [comment]
正在开发阿B的登录功能

**Comment by Chokppl** [comment]
> 正在开发AB的登录功能

聚合直播上看B站画质还是正常的

**Comment by xiaoyaocz** [comment]
> > 正在开发AB的登录功能
> 
> 聚合直播上看B站画质还是正常的

聚合直播用的是旧接口，有些直播会看不了

**Comment by 1314Zeng** [comment]
哔哩哔哩画质是不是被蒙古上单干掉了，希望作者大大早点解决

**Comment by yancj9ya** [comment]
> 正在开发阿B的登录功能

大佬143能端上来了吗？我看发布又撤回了！

**Comment by xiaoyaocz** [comment]
> > 正在开发阿B的登录功能
> 
> 
> 
> 大佬143能端上来了吗？我看发布又撤回了！

还有点问题，周末调完再发版本
