### ISSUE TITLE
[Feature] 添加账户功能

### ISSUE THREAD

**Issue by aiqujun** [xiaoyaocz/dart_simple_live#212]
希望添加账户功能，可以参考纯粹直播app使用supabase开发的账户功能！

**Comment by aiqujun** [comment]
> 1.安卓tv，最好支持4.3的，不支持也没事毕竟乐视没多少人用！最好可以，还是有一部分的！😄😄😄 哪怕目前简单适配电视也行！ 2.希望添加账户功能，可以参考supabase！

**Comment by xiaoyaocz** [comment]
不会开发账户同步功能。
