### ISSUE TITLE
[Feature] 登陆询问是否过于频繁？

### ISSUE THREAD

**Issue by Qiihz** [xiaoyaocz/dart_simple_live#219]
添加哔哩哔哩登录功能后，每次打开直播间，都会有显示“哔哩哔哩需要登录才能观看高清直播，是否前往登录？”的对话框。我不知道这是否是一个 bug。

**Comment by xiaoyaocz** [comment]
不是BUG，不登录清晰度只有480P，基本没有观看体验。登录后就不会弹窗了。

**Comment by xiaoyaocz** [comment]
使用旧接口是可以做到不登录观看1080P，但是有一些分区的直播间是看不了的。
如：https://live.bilibili.com/31214230
