### ISSUE TITLE
[BUG] iOS后台仅播放音频一段时间回来，大量堆积弹幕导致卡顿

### ISSUE THREAD

**Issue by realOxy** [xiaoyaocz/dart_simple_live#230]
**BUG内容**
iOS后台仅播放音频一段时间回来，大量堆积弹幕导致卡顿

**重现步骤**
1. 全屏打开热门的有弹幕的直播间
2. 滑倒后台
3. 一段时间后回来，大量弹幕导致卡顿

**截图或视频**
![IMG_1703](https://github.com/xiaoyaocz/dart_simple_live/assets/70512220/9fc0da63-9434-4c83-94f2-77ced5fe99b2)

**平台信息**
 - 设备: iPhone 14
 - 系统版本: iOS 17.1
 - APP版本: 1.4.4

**Comment by tomtol404** [comment]
你好，请问你ios17.1是怎么安装上的成功的？我这边安装，提示无法验证其完整性
