### ISSUE TITLE
[Feature]观看历史记录优化

### ISSUE THREAD

**Issue by tewsss** [xiaoyaocz/dart_simple_live#231]
**描述**
目前观看历史放在了“我的”一栏中，希望优化如下
1，目前只有一键清空，希望单独删除某条历史记录，可通过左滑或者右滑删除的方式

2，在全屏看直播状态下，屏幕右边边缘向左滑动，可以调出历史观看记录
方便跳转之前看过的直播

**Comment by aiqujun** [comment]
我没记错的话可以长按删除某一个！有可能只有安卓可以！

**Comment by tewsss** [comment]
是的，常按可以删除，滑动的交互会更方便些
