### ISSUE TITLE
[BUG] 横屏首页左侧有分割线

### ISSUE THREAD

**Issue by yuhouchen14** [xiaoyaocz/dart_simple_live#235]
**BUG内容**
输入BUG详细内容
如题 升级145出现 四个tab页面左侧均出现错位

**重现步骤**
请在此输入重现步骤
1. 打开即有
2. xxx
3. xxx

**截图或视频**

![3BB59937-D0AF-44F0-8D98-1DBF300E511F](https://github.com/xiaoyaocz/dart_simple_live/assets/150273941/35953725-4a3e-49d0-80f2-ce3a9fb85579)

**平台信息**
 - 设备: [e.g. iPhone13]
 - 系统版本: [e.g. ios15.6]
 - APP版本: [e.g. 145]

**Comment by xiaoyaocz** [comment]
设置-主页设置

**Comment by yuhouchen14** [comment]
> 设置-主页设置

不是这个意思 你看截图左侧有一条缝隙 只有主页这几个界面有错位  iPhone圆角下特别明显
