### ISSUE TITLE
[Feature]横屏模式下方白条占空间

### ISSUE THREAD

**Issue by the-Stupid** [xiaoyaocz/dart_simple_live#236]
![Screenshot_2023-11-09-18-22-11-212_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/46675733/5bfa80a8-b3ab-4e2d-838e-2502a0028549)
如题，下方白条作用不大，浪费了大块空间

**Comment by xiaoyaocz** [comment]
系统默认行为，无计划修改
