### ISSUE TITLE
[Feature] 在移动数据和Wi-Fi情况下分别设置默认播放画质

### ISSUE THREAD

**Issue by ShimaRain** [xiaoyaocz/dart_simple_live#237]
在我的-设置-默认清晰度设置里分别添加Wi-Fi下默认清晰度和移动数据默认清晰度

**Comment by aiqujun** [comment]
那在添加一个移动网络提醒

**Comment by xinghuoyao** [comment]
1.4.7版，默认清晰度设置最高，数据网络清晰度设置最低，在使用移动数据时依然是最高画质。设备小米13，miui14的安卓系统
![dff3371bb8e5e31c493ba798800d372](https://github.com/xiaoyaocz/dart_simple_live/assets/98877139/b07be247-cdcf-4982-9866-009cac35b071)
![bd2534919cb38d3eb5674be394be586](https://github.com/xiaoyaocz/dart_simple_live/assets/98877139/ad357c4c-4e06-42ee-84bf-7ace8b48d394)

**Comment by xiaoyaocz** [comment]
> 1.4.7版，默认清晰度设置最高，数据网络清晰度设置最低，在使用移动数据时依然是最高画质。设备小米13，miui14的安卓系统 更新：我手机重启了下就没问题了，可能是我自己的问题 ![dff3371bb8e5e31c493ba798800d372](https://private-user-images.githubusercontent.com/98877139/295786618-b07be247-cdcf-4982-9866-009cac35b071.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Mjc2MjcsIm5iZiI6MTcwNTYyNzMyNywicGF0aCI6Ii85ODg3NzEzOS8yOTU3ODY2MTgtYjA3YmUyNDctY2RjZi00OTgyLTk4NjYtMDA5Y2FjMzViMDcxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAxMjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZThiMDI4MDIxYTZmY2M5MzFhODRmMTg0ZmEyNjNkOTc4NmZmNTAxOGNhYjQ1ZTVkYzhlMWI4YWQzMTRjMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BMWn7NRNH9XftcNi0paRwcPXQTLOTAONU_pIqQk0Tkk) ![bd2534919cb38d3eb5674be394be586](https://private-user-images.githubusercontent.com/98877139/295786635-ad357c4c-4e06-42ee-84bf-7ace8b48d394.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Mjc2MjcsIm5iZiI6MTcwNTYyNzMyNywicGF0aCI6Ii85ODg3NzEzOS8yOTU3ODY2MzUtYWQzNTdjNGMtNGUwNi00MmVlLTg0YmYtN2FjZThiNDhkMzk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAxMjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MTAxYTM5MDU0MWZiY2FhMmFkZTkzNzM4N2ZiNDYwMDVhZDkwNThhNjUwODEyMjRmZmNjZTg0OTUzYzlmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NkLJqphORq_60bSa_-ZrhJ8vE59uBR0g4WipPIlY_Cc)

应该是你开了VPN的问题，VPN会被识别成一个独立的网络类型
