### ISSUE TITLE
ios17.1.1无法安装此app

### ISSUE THREAD

**Issue by tomtol404** [xiaoyaocz/dart_simple_live#242]
**BUG内容**
输入BUG详细内容
提示无法安装此app，因为无法验证其完整性

**重现步骤**
请在此输入重现步骤
1. 通过mac下载1.4.5和1.4.4版本的ipa文件
2. 通过隔空投送到iphone，点击安装，提示提示无法安装此app，因为无法验证其完整性
3

**截图或视频**
![IMG_0539](https://github.com/xiaoyaocz/dart_simple_live/assets/132876931/67e0d8aa-4b53-49c4-88b5-bf916ef0e4b2)

**平台信息**
 - 设备: [e.g. iPhone14]
 - 系统版本: [e.g. ios17.1.1]
 - APP版本: [e.g. 1.4.5 or 1.4.4]

**Comment by xiaoyaocz** [comment]
使用Sideloadly等工具自签安装
