### ISSUE TITLE
[BUG] 极米z6xpro安装后按ok无效

### ISSUE THREAD

**Issue by WuJelly** [xiaoyaocz/dart_simple_live#245]
**BUG内容**
输入BUG详细内容
【请务必填写详细信息方便定位问题】
【反馈前先查找下是否存在相似的Issues】

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**
在这里贴上截图或视频

**平台信息**
 - 设备: [e.g. iPhone6]
 - 系统版本: [e.g. Android 10.0]
 - APP版本: [e.g. 22]

**Comment by xiaoyaocz** [comment]
暂不支持TV端。合并#15
