### ISSUE TITLE
[BUG]深色主界面最左侧有一条浅色竖线

### ISSUE THREAD

**Issue by A13xMogh** [xiaoyaocz/dart_simple_live#246]
深色主界面最左侧有一条浅色竖线，ios与安卓平台都存在。

![F62911B1-3B84-4D8F-9EFF-2608045ECD01](https://github.com/xiaoyaocz/dart_simple_live/assets/116833727/c919bf13-27bd-4be3-a277-9ccf728cd03d)

**平台信息**
 - 设备: [iPhone13 mini，红米4高配]
 - 系统版本: [ios15.6，Android 11]
 - APP版本: [1.4.5]

**Comment by xiaoyaocz** [comment]
合并 #235
