### ISSUE TITLE
[BUG] 退到后台不会自动暂停

### ISSUE THREAD

**Issue by lovelymeng** [xiaoyaocz/dart_simple_live#254]
**BUG内容**
荣耀30鸿蒙系统4.0.0退到后台不会自动暂停，一直有直播声音

**平台信息**
 - 设备: [荣耀30]
 - 系统版本: [鸿蒙4.0.0]
 - APP版本: [1.4. 5]

**Comment by xiaoyaocz** [comment]
这不是BUG，部分人需要在后台播放。后续加个开关控制。
