### ISSUE TITLE
在Flyme上进入后台播放应用会被杀掉

### ISSUE THREAD

**Issue by Chokppl** [xiaoyaocz/dart_simple_live#265]
软件设定允许自启动后台运行并在电池优化中设定无限制后台还是会被杀掉，播放状态系统有运行中的播放进程，此时进入后台后软件全部进入缓存，这个有可能是系统误杀掉的原因。
可否添加这种设定一个保活的通知，保活之余也可以在后台播放后通过下拉状态栏点击通知在任意三方界面回到前台直播界面。

![S31217-22224384_com android systemui](https://github.com/xiaoyaocz/dart_simple_live/assets/142749179/50f328e7-63c9-4bda-9efb-17f7d84ed9ef)
![S31217-22225874_com android settings](https://github.com/xiaoyaocz/dart_simple_live/assets/142749179/5944aae4-56fe-4e83-8588-0bc0e347c243)

 - 设备: Meizu 17Pro
 - 系统版本: Android 13
 - APP版本: 1.4.5

**Comment by xiaoyaocz** [comment]
合并 #216
