### ISSUE TITLE
iOS版闪退

### ISSUE THREAD

**Issue by chea08** [xiaoyaocz/dart_simple_live#266]
ios端安装1.0.13版本无法打开，闪退。
机型是13pm，系统为ios16.5 1。
安装方式：使用trollstore安装，trollstore版本为2.0.8

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Or2z** [comment]
打开手机开发者模式就不会闪退了
