### ISSUE TITLE
斗鱼没法观看了，希望作者能够解决下

### ISSUE THREAD

**Issue by 1314Zeng** [xiaoyaocz/dart_simple_live#27]
/
![Uploading 144F04CC-8760-4F4E-88D9-5DC300FB1F34.png…]()

**Comment by anwen-anyi** [comment]
坐等大佬更新~

**Comment by xiaoyaocz** [comment]
[已更新](https://github.com/xiaoyaocz/dart_simple_live/releases)

**Comment by anwen-anyi** [comment]
> [已更新](https://github.com/xiaoyaocz/dart_simple_live/releases)

已更新完毕 可用了，不过还有哪个 斗鱼无法搜索的可以修复下吗

**Comment by 1314Zeng** [comment]
> 

大佬辛苦了，这是我苹果手机上唯一看直播的好软件，希望大佬能够越做越好，我们会一直支持你的😄
