### ISSUE TITLE
很多直播间没法看了，网页上可以正常看

### ISSUE THREAD

**Issue by WaterSeekingFish** [xiaoyaocz/dart_simple_live#28]
rt
![Screenshot_2023-06-15-21-23-45-874_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/30098930/b85d30e2-9f14-4125-899e-1a3ffe31eacf)

**Comment by xiaoyaocz** [comment]
[已更新](https://github.com/xiaoyaocz/dart_simple_live/releases)
