### ISSUE TITLE
[BUG] iOS请求添加返回桌面停止后台声音播放设置

### ISSUE THREAD

**Issue by gujiaming2022** [xiaoyaocz/dart_simple_live#284]
**BUG内容**
iOS请求添加返回桌面停止后台声音播放

**重现步骤**
请在此输入重现步骤
 • 打开直播后返回桌面无法关闭直播声音，一直在后台播放，需要手动暂停才可以。

**截图或视频**
在这里贴上截图或视频

**平台信息**
 - 设备: [ iPhone 13 Pro Max]
 - 系统版本: [iOS17.0]
 - APP版本: [1.4.7 ]

**Comment by xiaoyaocz** [comment]
设置-直播间设置-进入后台自动暂停

**Comment by gujiaming2022** [comment]
iOS客户端并没有相关按钮
![IMG_5182](https://github.com/xiaoyaocz/dart_simple_live/assets/59131675/4adb66e2-b04f-4c2a-86db-8e7f03f6e16b)

**Comment by xiaoyaocz** [comment]
下载这个版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/7442645338

**Comment by gujiaming2022** [comment]
> 下载这个版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/7442645338

OK，这个版本可以了，感谢。
