### ISSUE TITLE
[BUG] 抖音内容加载失败

### ISSUE THREAD

**Issue by GodKingLi** [xiaoyaocz/dart_simple_live#285]

**Comment by xiaoyaocz** [comment]
下载此版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/7442645338

**Comment by yuhouchen14** [comment]
> 下载此版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/7442645338

尝试多次 似乎此修复版巨魔不能正常安装 提示unable to locate app bundle inside the .ipa archive 自签没有尝试

**Comment by xiaoyaocz** [comment]
> > 下载此版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/7442645338
> 
> 尝试多次 似乎此修复版巨魔不能正常安装 提示unable to locate app bundle inside the .ipa archive 自签没有尝试

下载的是zip文件，需要先解压

**Comment by yuhouchen14** [comment]
> > > 下载此版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/7442645338
> > 
> > 
> > 尝试多次 似乎此修复版巨魔不能正常安装 提示unable to locate app bundle inside the .ipa archive 自签没有尝试
> 
> 下载的是zip文件，需要先解压

抱歉没注意 测试抖音搜索与分类均正常工作

**Comment by Rachel2373** [comment]
使用最新1.4.7版本的windows端软件，抖音扔无法观看。
1.关注列表中，正在直播的抖音房间显示未直播；
2.主页的抖音列表中，显示【发送get请求失败，点击刷新】

**Comment by timegiveyour** [comment]
![38A2E0D3-898E-4972-98A3-7B5C3DA52342](https://github.com/xiaoyaocz/dart_simple_live/assets/166782725/979b90ca-5364-4747-9528-9d462ff6129c)
