### ISSUE TITLE
[Feature] 电视端可行性分析

### ISSUE THREAD

**Issue by li5bo5** [xiaoyaocz/dart_simple_live#292]
**描述**
手机端需要平台聚合的场景并不是很有必要，因为手机端是可以打开任务栏栏进行切换app，有了您的这个app只是让操作更加便捷
然而，安卓电视端，是不能打开任务栏，不能随意切换app，每次切换斗鱼虎牙的直播间都要退出重进，实在是太麻烦；
而且，现在电视大屏看直播更爽。
所以安卓电视端更有必要进行开发！！！
此外，TV端需要的功能更少

**附加**
直播间里面设置的项目，可以参考斗鱼官方的app
[斗鱼.zip](https://github.com/xiaoyaocz/dart_simple_live/files/13896040/default.zip)
各个平台的切换模式，可以参照tvbox
https://github.com/CatVodTVOfficial/TVBoxOSC
还有个同类型的APP，这个对电视支持也就一般
https://github.com/liuchuancong/pure_live
希望作者出马、给电视端带来福音！！

**Comment by xiaoyaocz** [comment]
#15
