### ISSUE TITLE
[BUG] 抖音搜索与跳转

### ISSUE THREAD

**Issue by dongbao66** [xiaoyaocz/dart_simple_live#299]
如图
![fe682004e72ece9f8cb9c1066d5651a7](https://github.com/xiaoyaocz/dart_simple_live/assets/95880227/ff239ad6-6f97-4d9b-b7a9-29169a1f1797)
![7e6f5d61cf367d611bb648a03717bb8d](https://github.com/xiaoyaocz/dart_simple_live/assets/95880227/c236ab3e-6839-46d6-99f9-c200801eaa32)

**Comment by dongbao66** [comment]
代发酷友的问题

**Comment by xiaoyaocz** [comment]
跳转只支持 https://live.douyin.com/134602031404 这种链接

**Comment by kissfire1995** [comment]
> 跳转只支持 https://live.douyin.com/134602031404 这种链接

抖音的分区和搜索都不好使

**Comment by zdb94** [comment]
> 跳转只支持 https://live.douyin.com/134602031404 这种链接

新版本抖音的搜索报错，旧版本1.4.5可以

**Comment by kissfire1995** [comment]
> > 跳转只支持 https://live.douyin.com/134602031404 这种链接
> 
> 新版本抖音的搜索报错，旧版本1.4.5可以

谢谢老哥 我看它更新日志以为只有新版本修复抖音了

**Comment by luckfalcon** [comment]
这个抖音搜索功能崩溃了吗？已经很久了，要加紧修复bug了。
