### ISSUE TITLE
[BUG] 抖音直播间加载速度问题

### ISSUE THREAD

**Issue by withered233** [xiaoyaocz/dart_simple_live#302]
**BUG内容**
打开抖音直播间大概率出现“过长时间加载(状态栏在跑流量)”，需要13s左右才显示视频内容。
但是如果在加载几秒后手动从默认flv切换到hls线路，就能立刻显示视频内容。
测试直播间 https://live.douyin.com/misacat33

**截图或视频**
录了个视频 https://easylink.cc/keng61 ，前段是长时间加载，后段是切换线路秒载。

**平台信息**
  Flyme Android 13
  APP版本: 1.4.7

**Comment by xiaoyaocz** [comment]
#115
