### ISSUE TITLE
[Feature] 请填写简短易读的标题

### ISSUE THREAD

**Issue by iKun10001** [xiaoyaocz/dart_simple_live#306]
**描述**
输入具体的功能描述
【反馈前先查找下是否存在相似的Issues】
【如果你有多个建议、请求，请分开提交Issues】
大佬可以加几个境外的直播吗  比如 blog YouTube  afreecatv   然后给这些直播加个代理设置  支持socks5 http代理就好了 
**附加**
请附加相关截图、视频或链接（好让我知道要我抄哪个APP）

**Comment by xiaoyaocz** [comment]
无计划
