### ISSUE TITLE
[BUG] 抖音概率报错

### ISSUE THREAD

**Issue by withered233** [xiaoyaocz/dart_simple_live#307]
**BUG内容**
抖音分区及直播间有较高概率出现报错。
报错内容-----分区：无权限访问资源403（这时候列表抖音直播间无法获取状态）
------直播间：FormatException:Unexpected end of input (atcharacter 1)
(直播间均为开播状态)
**重现步骤**
从更新1.4.8后遇到的，较大概率出现，报错后反复重启app或等1分钟左右再进入就会好，不清楚是抖音抽风还是app原因。
**截图或视频**
![S40212-01491881_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/60478611/3bdd6866-0872-4bed-976a-ceb5ae3eda8d)
![S40212-01484767_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/60478611/3c552d8e-b92a-43c2-9152-796b048afc94)

**平台信息**
 魅族17
 flyme10
 APP版本:1.4.8

**Comment by inoyna12** [comment]
+1，我的也是经常出现这个错误，但我是直接开关一下飞行模式就能看了，不知道是不是跟ip地址有关

**Comment by xiaoyaocz** [comment]
抖音风控

**Comment by zhusuner** [comment]
我也遇到了😭
![IMG_20240220_230912](https://github.com/xiaoyaocz/dart_simple_live/assets/80241679/88c1654e-7f94-4f7c-a256-eab0344deaed)

**Comment by inoyna12** [comment]
我大概知道原因了，每次打开关注用户那里的界面，当前ip地址会查询多个抖音用户的id，看他们有没有开直播，短时间频繁查询就会导致抖音风控ip，需要等大概半分钟才能观看直播，或者换ip立马观看
@xiaoyaocz

**Comment by xiaoyaocz** [comment]
抖音风控问题，暂时无法解决
