### ISSUE TITLE
[BUG] 关注列表不能实时更新需要重启软件才行

### ISSUE THREAD

**Issue by Seal-chan** [xiaoyaocz/dart_simple_live#309]
**BUG内容**
输入BUG详细内容
关注列表不能实时更新需要重启软件才行
希望改进
Ver 1.4.8

**Comment by yancj9ya** [comment]
点一下那个爱心就能再次更新一次关注主播的状态

**Comment by xiaoyaocz** [comment]
实时更新做不到。1.6.0已增加”刷新“按钮，可以手动刷新状态。
