### ISSUE TITLE
[BUG] 请填写简短易读的标题

### ISSUE THREAD

**Issue by Ssssofar** [xiaoyaocz/dart_simple_live#312]
虎牙部分直播间在打开后10s内必出现卡顿现象，短则1s，长则4-5s 。

**重现步骤**
请在此输入重现步骤
1. 打开虎牙直播间（例如：狂鸟丶楚河直播间）
2. 出现直播画面后，等待8s左右即出现卡顿

**重现BUG视频**

https://github.com/xiaoyaocz/dart_simple_live/assets/137623880/ac46fc46-6b65-49c2-a4e8-a5bb74dbdc0d

**平台信息**
 - 设备: [红米note12Turbo]
 - 系统版本: [Android 14.0]
 - APP版本: [1.4.8]

**Comment by xiaoyaocz** [comment]
#317
