### ISSUE TITLE
[BUG] 虎牙直播观看自动中断

### ISSUE THREAD

**Issue by luckfalcon** [xiaoyaocz/dart_simple_live#317]
https://github.com/xiaoyaocz/dart_simple_live/assets/77876802/e07fc928-37be-4318-9de5-00cd622f317d

**Comment by rikka5201** [comment]
出现相同问题，直播时会黑屏卡顿，然后自动切换线路，切到线路四提示加载失败

**Comment by yancj9ya** [comment]
出现相同问题windows端

**Comment by yicun0316** [comment]
一样问题

**Comment by eureka6** [comment]
相同问题，虎牙平台会像楼上视频那样一卡一卡。

**Comment by JZSTAR01** [comment]
同出问题，虎牙平台

**Comment by 2427196689** [comment]
1小时前出现，虎牙平台

**Comment by Seal-chan** [comment]
相同问题，windows端，虎牙

**Comment by xiaofanzii** [comment]
mac、ios、ipados均出现此问题

**Comment by yibingchaoyue** [comment]
加1

**Comment by kumu7y** [comment]
应该是虎牙添加了验证

**Comment by JackA1ltman** [comment]
> 应该是虎牙添加了验证

不是这个原因，隔壁类似软件正常播放

**Comment by YWZMCH** [comment]
JustLive也出现类似问题，播放几秒自动暂停


> > 应该是虎牙添加了验证
> 
> 不是这个原因，隔壁类似软件正常播放

**Comment by YWZMCH** [comment]
> > 应该是虎牙添加了验证
> 
> 不是这个原因，隔壁类似软件正常播放

JustLive也出现类似问题，虎牙播放几秒自动暂停

**Comment by gg55gg55** [comment]
出问题了😭，卡，刷新

**Comment by changxiangyou** [comment]
是的 虎牙直播中断

**Comment by changxiangyou** [comment]
> 相同问题，虎牙平台会像楼上视频那样一卡一卡。
> 
> 之后会弹窗报错，提示：`播放失败，faild to open https://xxx`

相同

**Comment by shuijiao1** [comment]
相同问题，就虎牙会这样

**Comment by s21y10q45** [comment]
昨天问题出现我以为只是我的问题 今天凌晨又没问题现在又不行了

**Comment by jzt123** [comment]
设备：小米平板6pro
系统版本：14.0.2
软件版本：1.4.8
也是同样的问题
![Screenshot_2024-02-24-17-30-18-868_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/69405173/4a484d38-c6ce-4fac-9dbf-8da6eba61772)

斗鱼没有这个问题，虎牙有

**Comment by gg55gg55** [comment]
什么时候更新一下😧求更新

**Comment by liu7526539** [comment]
在iOS平台和Windows上，虎牙一直切换线路，最后报错

**Comment by yancj9ya** [comment]
> 什么时候更新一下😧求更新

这玩意涉及到断开的原因定位，怕是不那么好修复，我记得之前虎牙也有这个毛病，是通过切换flv的这个源修复的，但是现在flv也有这个东西了！具体虎牙的服务器的判定方式和原理得摸清了才能修复估计

**Comment by kumu7y** [comment]
> > 什么时候更新一下😧求更新
> 
> 这玩意涉及到断开的原因定位，怕是不那么好修复，我记得之前虎牙也有这个毛病，是通过切换flv的这个源修复的，但是现在flv也有这个东西了！具体虎牙的服务器的判定方式和原理得摸清了才能修复估计

我猜测应该是检测登录，虎牙网页端，登录后是可以观看的，但是不登录会一直提示需要扫码登录

**Comment by Tartarus2014** [comment]
主要是看获取直链的方式， 每个方式都有对应的参数， 参数不过就被拦截断流了

**Comment by xiaofanzii** [comment]
> > > 什么时候更新一下😧求更新
> > 
> > 这玩意涉及到断开的原因定位，怕是不那么好修复，我记得之前虎牙也有这个毛病，是通过切换flv的这个源修复的，但是现在flv也有这个东西了！具体虎牙的服务器的判定方式和原理得摸清了才能修复估计
> 
> 我猜测应该是检测登录，虎牙网页端，登录后是可以观看的，但是不登录会一直提示需要扫码登录

macos的虎牙客户端不需要登录也能一直看并且不限制蓝光画质啥的。不知道win的客户端需不需要登陆。没有win系统电脑测试。不过网页端的几分钟就不行了，并且还限制画质。

**Comment by feranwq** [comment]
考虑改成登录的吧，这种免登录接口应该都不长久。

**Comment by jhinzzz** [comment]
相同问题。

**Comment by luckfalcon** [comment]
> 登录

不一定，因为我可以将这个app 里获得的直播流放在VLC 里看，流畅不卡顿，VLC看直播唯一一点不好的就是看不到弹幕，而看直播乐趣之一就是看弹幕，如果对弹幕不感兴趣，甚至喜欢屏蔽弹幕的人，那vlc 通过直播源方式看，都不需要自己主动屏蔽弹幕了

**Comment by wujiyu115** [comment]
https://github.com/youshandefeiyang/LiveRedirect/blob/main/Golang/liveurls/huya.go 老哥可以看看这个解析，我用这个算法是可以一直播放的 @xiaoyaocz

**Comment by pcccccc** [comment]
解决建议：修改播放器UA为flv.js或HYPlayer

**Comment by xiaoyaocz** [comment]
[v1.4.9](https://github.com/xiaoyaocz/dart_simple_live/releases/tag/v1.4.9)

**Comment by chenhy22tw** [comment]
我試了好幾次，用1.4.9 版在我的安卓手機和電視盒上只能看兩分鐘就自動黑屏不能看了，可是我用另外一個網站下載的app, HuYa-2.1.0-20240223.apk 裡的娱乐天地里的一起看里的虎牙，看阿斗归来了人家是正常的，给你参考。下载地址我是 https://www.fenxm.com/1027.html

**Comment by chenhy22tw** [comment]
里面还有四线路，默认的阿里的线路是可正常观看阿斗归来了的

**Comment by chenhy22tw** [comment]
附上他的源他码、https://github.com/jayjd/huyatv/releases/tag/2.1.0

**Comment by chenhy22tw** [comment]
https://github.com/jayjd/HuYaTv/issues/21

**Comment by chenhy22tw** [comment]
大哥，加油。可以的話想請你喝奶茶。

**Comment by caobio** [comment]
iOS 1.4.9最新版看虎牙直播还是会出现自动中断
