### ISSUE TITLE
[BUG] 播放失败乱码

### ISSUE THREAD

**Issue by zhemuxunxiang** [xiaoyaocz/dart_simple_live#319]
**BUG内容**
输入BUG详细内容
Wi-Fi 情况下播放不了直播，流量播放也不稳定，一会儿一转圈，而且转圈次数多了就提示播放失败加乱码，Wi-Fi 情况下直接就播放失败加乱码，但是 Wi-Fi 的时候有时候能播放，所有平台都是，设置里面的硬件解码和兼容模式开关来回调试都没用。

**重现步骤**
请在此输入重现步骤
1. 打开直播
2. 随意进入直播间
3. 播放失败

**截图或视频**
https://github.com/xiaoyaocz/dart_simple_live/assets/101083034/e3ac135d-e3bd-4fc8-9730-a19e2a054130
![Screenshot_20240224_205929.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/101083034/90a6eb57-177e-451f-9ce0-dc7fddc8dddd)

**平台信息**
 - 设备: iqoo10Pro
 - 系统版本: Android 14
 - APP版本: 1.4.8

**Comment by lyt3905** [comment]
提过issue了

**Comment by xiaoyaocz** [comment]
#317
