### ISSUE TITLE
[BUG] PC端，在播放直播按左上角返回，会将显示器亮度调为100%

### ISSUE THREAD

**Issue by ChenDY2233** [xiaoyaocz/dart_simple_live#332]
**BUG内容**
PC端，在观看直播时，如果点击左上角的返回，就会将显示器屏幕亮度瞬间调为100%，我是习惯低亮度的。简直一瞬间闪瞎眼

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**
在这里贴上截图或视频

**平台信息**
 - 设备: PC台式
 - 系统版本: Windows 10 专业版 21H1
 - APP版本: 1.4.9

**Comment by the-Stupid** [comment]
而且之后没法手动调回去，调节亮度的条是灰的
