### ISSUE TITLE
[Feature] PC端刷新直播间状态

### ISSUE THREAD

**Issue by Hor1Zzon** [xiaoyaocz/dart_simple_live#334]
希望能在直播间的时候可以刷新更新别的直播间状态，不然每次都要退出直播间点小心心刷新，
![1709722878542](https://github.com/xiaoyaocz/dart_simple_live/assets/120663526/d7c330e8-1201-45af-92b9-4514d8623bbb)
比如我这个图，关注列表旁边可以来一个刷新按钮，就不用退出直播间了。
此外退出直播间，进入主页面的时候，希望能有自动变成小窗功能，这样也能去搜别的直播间或者刷新直播间状态。

**Comment by rikka5201** [comment]
加一，手机端可以下拉刷新，希望桌面端可以下拉或者按钮刷新
