### ISSUE TITLE
pop_os（基于ubuntu）上安装后无法打开

### ISSUE THREAD

**Issue by ashakii** [xiaoyaocz/dart_simple_live#335]
pop_os（基于ubuntu）上安装后无法打开

**Comment by ashakii** [comment]
下载压缩文件尝试，提示ashakii@pop-os:~/下载/simple_live_app-1.4.9+10409-linux$ simple_live_app 
simple_live_app: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory

**Comment by ashakii** [comment]
已经解决，安装libmpv就好了

**Comment by expoli** [comment]
Arch Linux上需要执行下面的这条命令

```bash
sudo ln -s /usr/lib/libmpv.so /usr/lib/libmpv.so.1
```
