### ISSUE TITLE
虎牙直播再次出现卡顿

### ISSUE THREAD

**Issue by zxz02** [xiaoyaocz/dart_simple_live#339]
**BUG内容**
输入BUG详细内容
【请务必填写详细信息方便定位问题】
【反馈前先查找下是否存在相似的Issues】

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**
在这里贴上截图或视频

**平台信息**
 - 设备: [e.g. iPhone6]
 - 系统版本: [e.g. Android 10.0]
 - APP版本: [e.g. 22]

**Comment by zxq0822** [comment]
是的，虎牙线路又出问题了！大佬快修复

**Comment by leomessi1125** [comment]
huawei matepad11 播放途中黑屏卡顿，间歇性2-3秒一黑屏

**Comment by Xsoong** [comment]
确实，虎牙又出问题了

**Comment by mochu18** [comment]
**设备：** Windows 11  
**系统版本：** 23H2  
**APP版本：** 1.4.9

https://github.com/xiaoyaocz/dart_simple_live/assets/57317830/3f2d635e-faad-44e9-b123-0c04901b56b9

**看着会不断刷新直播页面**

**Comment by JZSTAR01** [comment]
+1

**Comment by xwlittle** [comment]
+1

**Comment by gg55gg55** [comment]
是的大佬求更

**Comment by mmzy12** [comment]
+1！

**Comment by U2ii** [comment]
+1

**Comment by Yeezy0702** [comment]
+1 试了下直链解析加 nplayer，显示 forbidden 403 有可能是虎牙ban 了接口解析的问题吗

**Comment by rayae** [comment]
看了上次修复时候的提交记录，如果还是UA被ban的话，希望能加入随机UA生成的功能

**Comment by shuijiao1** [comment]
+1

**Comment by Seal-chan** [comment]
跟上次一样的问题

**Comment by lovelymeng** [comment]
+1

**Comment by xiaoyaocz** [comment]
有空就修
