### ISSUE TITLE
虎牙和斗鱼直播间出现卡顿

### ISSUE THREAD

**Issue by bleedgreen0921** [xiaoyaocz/dart_simple_live#342]
**BUG内容**
输入BUG详细内容
【进入虎牙和斗鱼直播间卡顿，重复自动刷新】
【反馈前先查找下是否存在相似的Issues】

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**

Uploading RPReplay_Final1710302322.mp4…

**平台信息**
 - 设备: [e.g. iPhone14 plus]
 - 系统版本: [e.g. ios16.5]
 - APP版本: [e.g. 1.4.9

**Comment by xiaoyaocz** [comment]
#339
