### ISSUE TITLE
虎牙直播卡顿

### ISSUE THREAD

**Issue by 1areyouok** [xiaoyaocz/dart_simple_live#343]
**BUG内容**
播放虎牙直播会卡顿，直播线路会自动切换，转圈，换完就显示播放地址失败3.13日，前几天也是这样，所以才来提交问题的，希望修复，很喜欢这个软件，没有广告，每天必用，谢谢大佬

**截图或视频**
![5073a89a16174841f96fa726b84ad5d](https://github.com/xiaoyaocz/dart_simple_live/assets/163236047/eae52dea-7842-41e8-8dfc-f8a4b18ddc3f

**平台信息**
 - 设备: iPhone 14 pro   Windows10双平台都会
 - 系统版本: ios16.6.1  
 - APP版本: 最新版

**Comment by xiaoyaocz** [comment]
#339
