### ISSUE TITLE
ms安装包能不能给个信任证书？

### ISSUE THREAD

**Issue by gpronhub** [xiaoyaocz/dart_simple_live#348]
![图片](https://github.com/xiaoyaocz/dart_simple_live/assets/101042752/fb3db932-d832-4ae5-ac26-d8146ee7d93a)

**Comment by xiaoyaocz** [comment]
右键安装包-[属性]-[数字签名]-[详细信息]-[安装证书]-[本地计算机]-将证书放至[受信任的根证书颁发机构]-[完成]
