### ISSUE TITLE
[BUG] macos 打开同步失败

### ISSUE THREAD

**Issue by jiz4oh** [xiaoyaocz/dart_simple_live#351]
**BUG内容**
mac 端无法启动数据同步，显示 `HTTP服务未启动：SocketException: Failed to create server socket (OS Error: Operation not permitted, errno = 1), address = 0.0.0.0, port = 23234，请尝试重启应用`。搜索之后发现可能和 macos 的权限设置有关
<img width="757" alt="image" src="https://github.com/xiaoyaocz/dart_simple_live/assets/41264693/e8ab6ed8-be25-45ef-a079-2469c42114de">

**重现步骤**
macos 端打开数据同步

**截图或视频**
<img width="686" alt="image" src="https://github.com/xiaoyaocz/dart_simple_live/assets/41264693/dd9d95f9-7a13-418f-a9a0-969d51e36f78">

**平台信息**
 - 设备: macbookpro m1
 - 系统版本: 12.6
 - APP版本: 1.5.3

**Comment by cat-sir** [comment]
我也遇到了这个问题,大佬加油,希望能有解决方式
