### ISSUE TITLE
跟SimpleLiveTVOS的同步

### ISSUE THREAD

**Issue by opopopipipip** [xiaoyaocz/dart_simple_live#356]
老哥你好，SimpleLiveTVOS，说是对你这个项目的补充

我群里跟开发者也提过多端同步，他说技术上问题不大，可能涉及到用户和icloud等，只要两边能够配合的话应该可以，看你要不要找他聊聊看？

**Comment by xiaoyaocz** [comment]
参考：https://github.com/xiaoyaocz/dart_simple_live/blob/master/simple_live_tv_app/lib/services/sync_service.dart
只需要几个HTTP接口即可收到APP的数据推送，并不需要什么特殊处理

**Comment by pcccccc** [comment]
😂做好了，Testflight更新吧。
