### ISSUE TITLE
[BUG] 请查看图片

### ISSUE THREAD

**Issue by shaoyouvip** [xiaoyaocz/dart_simple_live#358]
**BUG内容**
输入BUG详细内容

**重现步骤**
请在此输入重现步骤
我关注了很多主播后就出现这个问题了 上传图片了

**截图或视频**

![屏幕截图 2024-03-26 005651](https://github.com/xiaoyaocz/dart_simple_live/assets/45180881/dc79fc3c-9006-4103-8a02-9e740c23975d)

**平台信息**
 - 设备: [e.g. iPhone6]
 - 系统版本: [e.g. Android 10.0]
 - APP版本: [e.g. 22]

**Comment by xiaoyaocz** [comment]
抖音风控，只能换网络或等一会再试
