### ISSUE TITLE
[Feature] 关于用户平台关注列表请求

### ISSUE THREAD

**Issue by geschirrt1** [xiaoyaocz/dart_simple_live#362]
请问可不可以支持获取平台用户关注列表，因为我在使用时发现，如果不知道目标直播间房间号或者是名字，搜不出来对应房间，其次是有个别平台我有很多关注的用户，如果一个个去输入添加，非常繁琐，能不能添加一个可以获取绑定账户的关注列表功能/开关？可能我描述不太清晰，先抱歉了。最后，非常感谢你的作品！

**Comment by xiaoyaocz** [comment]
无计划开发账户登录相关功能。
