### ISSUE TITLE
[Feature] 拖动小窗时被磁吸后关闭，能不能设置关闭这个功能？

### ISSUE THREAD

**Issue by hmmuaa** [xiaoyaocz/dart_simple_live#368]
**描述**
例如小窗现在在屏幕右下角，
我用拇指划一下，想把它丢到左下角，
结果每次都会被关闭小窗。

**附加**

![Screenshot_2024-04-05-14-16-53-85_e3cd25cd7d1683da6f376a9c501d0866](https://github.com/xiaoyaocz/dart_simple_live/assets/158799143/3e58ad80-add3-4628-9a02-b56354d1564d)

**Comment by xiaoyaocz** [comment]
系统行为，无法处理
