### ISSUE TITLE
[BUG] 抖音直播无法正常加载

### ISSUE THREAD

**Issue by SanJin1121** [xiaoyaocz/dart_simple_live#371]
**BUG内容**
1.关注界面中的正在直播的抖音直播没有正常显示；
2.关注界面中“直播中”和“开播中”有时不显示关注的抖音直播；
3.进入抖音直播窗口后出现错误提示(如图所示)，头像、名称等均无法正常加载。点击刷新，多次之后可能会加载成功；

**截图或视频**
![IMG_20240408_054728.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/166337343/6d8f5f57-c4c1-486f-bec5-1ded946a0619)
-----------
![IMG_20240408_054742.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/166337343/32739e54-e8f8-4f2a-9d74-66d47d576e70)
-----------
![IMG_20240408_054756.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/166337343/8e8ec968-6e2c-4f4a-9a35-b7d6f34f8e4c)
-----------
![IMG_20240408_054715.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/166337343/551b994f-08f3-4f2d-9f70-8f8c38c53a70)

**平台信息**
 - 设备: [Redmi note 10 Pro]
 - 系统版本: [Android 13 / MIUI 14.0.8.0]
 - APP版本: [1.5.3]

**Comment by xiaoyaocz** [comment]
#307 抖音风控问题，暂时无法解决。只能尝试更换网络环境或稍后再试。
