### ISSUE TITLE
[BUG] 安卓端导航条遮挡设置项

### ISSUE THREAD

**Issue by MonicaWQY** [xiaoyaocz/dart_simple_live#373]
**BUG内容**
安卓端导航条遮挡设置项，从链接解析里进入直播间最下方的关注、刷新、分享按钮也会被导航栏遮挡

**重现步骤**
1. 我的→直播设置
2. 首页→随便点进一个直播间→设置→弹幕设置
3. 我的→链接解析→链接跳转

**截图或视频**
![Screenshot_20240408_233849](https://github.com/xiaoyaocz/dart_simple_live/assets/93992899/bdc196b7-374e-4a48-b37b-5920fbe40a7a)
![Screenshot_20240408_233929](https://github.com/xiaoyaocz/dart_simple_live/assets/93992899/d460f1f5-512b-4ac6-8882-63c7b5f10851)

**平台信息**
 - 设备: [Samsung Galaxy S21 Ultra]
 - 系统版本: [Android 14.0]
 - APP版本: [1.5.3]

**Comment by YiDuoCiMei** [comment]
这个问题我也有，但我是平板，手机上面会使用手势所以这个问题不太明显，但是三星的平板下面有一个固定的底栏，这个问题会明显一些。

**Comment by YiDuoCiMei** [comment]
你好,回复邮件的你能看到吗？我有很多意见想提供给你,是一些改进,
很多与平板有关系,因为我使用比较多,
如果可以看到邮件,
我希望通过邮件发送给你,这包括手机、电脑的很多截图和说明,



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月4日(周二) 上午8:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaoyaocz/dart_simple_live] [BUG] 安卓端导航条遮挡设置项 (Issue #373)




 
Closed #373 as completed.
