### ISSUE TITLE
mac 同步 报错 socketException

### ISSUE THREAD

**Issue by cc1314who** [xiaoyaocz/dart_simple_live#375]
**BUG内容**
输入BUG详细内容
【请务必填写详细信息方便定位问题】
【反馈前先查找下是否存在相似的Issues】

**重现步骤**
请在此输入重现步骤
![Snipaste_2024-04-12_10-15-17](https://github.com/xiaoyaocz/dart_simple_live/assets/87588639/ef9ff241-1f46-4a35-95e8-6835fb8fa7d6)

**截图或视频**
![Snipaste_2024-04-12_10-14-12](https://github.com/xiaoyaocz/dart_simple_live/assets/87588639/fa7d3319-e6ee-4933-8c32-dc0619f4d0bd)

**平台信息**
 - 设备: mac
 - 系统版本: bigsur 11.2
 - APP版本: 1.5.3

**Comment by xiaoyaocz** [comment]
#351
