### ISSUE TITLE
[Feature] 支持抖音手机端分享的链接跳转

### ISSUE THREAD

**Issue by oblivion0421** [xiaoyaocz/dart_simple_live#376]
抖音手机端分享出来都是https://v.douyin.com/iYaMygyK/ 2@9.com :5pm这种链接，
如果要转换成https://live.douyin.com/808207714751 这种类型的链接，在手机上需要在浏览器打开一遍，然后请求桌面网站，用Safari需要转换两次才能出来可以跳转的链接。
可不可以直接在app里面直接集成转换功能。

**Comment by AMercyKiller** [comment]
目前使用https//live.douyin.com/xxx才能解析。xxx复制博主主页抖音号即可解析绝大多数博主。但是有一个缺点：就是抖音号可以使用标点符号，但是标点符号不会被simple live解析，会被忽略。比如抖音号Ab.cd会被认为是抖音号Abcd。所以可能一个博主的抖音号有标点符号导致可能进入不是想要的直播间。

**Comment by oblivion0421** [comment]
那可不可以添加一个抖音的https//live.douyin.com/这个模版在app里面，要不还要找这个模版好麻烦😂
发自我的 iPhone

> 在 2024年5月6日，01:44，AMercyKiller ***@***.***> 写道：
> https//live.douyin.com/

**Comment by AMercyKiller** [comment]
> 那可不可以添加一个抖音的https//live.douyin.com/这个模版在app里面，要不还要找这个模版好麻烦😂 发自我的 iPhone
> […](#)
> 在 2024年5月6日，01:44，AMercyKiller ***@***.***> 写道： https//live.douyin.com/

等开发者有空更新吧。看起来他挺忙的，耐心等待吧。
