### ISSUE TITLE
[BUG] 抖音直播无法搜索

### ISSUE THREAD

**Issue by Xxhn0** [xiaoyaocz/dart_simple_live#379]
**BUG内容**
无法搜索抖音直播房间。
【请务必填写详细信息方便定位问题】
【反馈前先查找下是否存在相似的Issues】

**重现步骤**
请在此输入重现步骤
1. 点击搜索。
2. 输入搜索内容。
3. 点击抖音直播tag

**截图或视频**
![Screenshot_2024-04-17-01-10-35-461_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/111640200/719b6b9b-8343-47e9-9172-0ead7b2e476c)

**平台信息**
 - 设备: [e.g. xiaomi 11pro]
 - 系统版本: [e.g. Android 14.0]
 - APP版本: [e.g. 1.5.3]

**Comment by GodKingLi** [comment]
是啊是啊 无法搜索 好难受

**Comment by HarrisRitari** [comment]
windows同样的错误

**Comment by shuke12306** [comment]
解决了吗
