### ISSUE TITLE
[BUG] 开播状态出错

### ISSUE THREAD

**Issue by yancj9ya** [xiaoyaocz/dart_simple_live#380]
![image](https://github.com/xiaoyaocz/dart_simple_live/assets/86911331/5cebee0e-4e81-42ac-adc3-1fd1edeef683)

显示未开播，实际点击进去是开播状态！

![image](https://github.com/xiaoyaocz/dart_simple_live/assets/86911331/7aa98378-61a0-4264-ae9c-c73b42a962fb)

**Comment by xiaoyaocz** [comment]
![image](https://github.com/xiaoyaocz/dart_simple_live/assets/16559082/14de9579-9048-43b3-8be7-36e8be77c9da)
