### ISSUE TITLE
[BUG] android tv不显示app图标

### ISSUE THREAD

**Issue by Joee-D** [xiaoyaocz/dart_simple_live#384]
**BUG内容**
chromecast with google tv 安装app后，主页不显示图标

**重现步骤**
1.安装app
2.首页不显示app图标
3.去设置-已安装app中可以看到app，可以正常打开使用

**截图或视频**
无

**平台信息**
 - 设备: chromecast with google tv 4k
 - 系统版本:  Android 12
 - APP版本: v1.0.3 beta

**建议**
androidTv使用android:banner来显示图标
https://developer.android.com/design/ui/tv/guides/system/tv-app-icon-guidelines?hl=zh-cn

建议增加android:banner字段（可能需要重绘图标）
https://github.com/xiaoyaocz/dart_simple_live/blob/4247c71fa4b4113386fccb5bffc962b811331b6c/simple_live_tv_app/android/app/src/main/AndroidManifest.xml#L9C9-L9C21

**Comment by afterward** [comment]
主activity中加这个即可
   
    <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
