### ISSUE TITLE
pc端直播间页面的关注列表不能主动刷新

### ISSUE THREAD

**Issue by xplore1578** [xiaoyaocz/dart_simple_live#387]
![5bea28ac1ffdd65fe868a4a97749f64](https://github.com/xiaoyaocz/dart_simple_live/assets/89838062/a995ccf8-b7cb-44e1-af91-75829ae2b710)
1.pc端直播间页面的关注列表不能主动刷新
2.希望音量条能有百分比显示

**Comment by xplore1578** [comment]
补充bug：应用最小化之后一段时间再打开 弹幕会糊成一团并且会卡顿 [直到弹幕完全飘走]
![Uploading c9b7615815c698828c055d106b2e1ca.png…]()

**Comment by xiaoyaocz** [comment]
#334
