### ISSUE TITLE
求疑：请问安卓1.5.3版本上抖音直播部分问题

### ISSUE THREAD

**Issue by geschirrt1** [xiaoyaocz/dart_simple_live#402]
**BUG内容**
153安卓移动端版本，抖音，现在不能在关注里看直播了，只能去历史里找来看，关注的不会刷新在关注列表内了，而且抖音区内，有些直播点进去只有弹幕和载入，没有画面和声音，另外之前就有的老问题，就是抖音不能使用搜索功能，其他没了，我只是单纯看几个游戏主播而已，部分反馈说关注多了看不了，我不确定我是不是也是这样，但我目前关注的抖音用户是四个，斗鱼五个个，虎牙俩个，bilibili一个，总计十二个关注

**平台信息**
 - 设备: [e.g. 红米note9]
 - 系统版本: [e.g. Android 12.0]
 - APP版本: 1.5.3

**Comment by geschirrt1** [comment]
代码403/401，然后抖音区直接就是无权限访问资源

**Comment by LY131022** [comment]
win版也是不能搜索了

**Comment by xiaoyaocz** [comment]
403/401就是触发抖音风控了，无解。只能尝试换个网络环境。
