### ISSUE TITLE
[BUG] 抖音直播突然没有弹幕了

### ISSUE THREAD

**Issue by NTCYE** [xiaoyaocz/dart_simple_live#407]
**BUG内容**
输入BUG详细内容
【请务必填写详细信息方便定位问题】
  今天看抖音直播突然没有弹幕了，一条也没有，但是界面也显示“弹幕服务器连接正常”
【反馈前先查找下是否存在相似的Issues】
  无

**重现步骤**
请在此输入重现步骤
 每次观看抖音直播

**截图或视频**
![Screenshot_2024-05-28-23-38-18-423_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/117371952/bd51b688-f7d6-4d93-97ad-34ad974932c3)

**平台信息**
- 设备: [小米10Pro]
- 系统版本: [Android 11.0，MIUI12.5.10稳定版]
- APP版本: [1.5.3]

**Comment by xiaoyaocz** [comment]
无法复现
