### ISSUE TITLE
[BUG] 虎牙直播全部看不了

### ISSUE THREAD

**Issue by shuijiao1** [xiaoyaocz/dart_simple_live#409]
**BUG内容**
虎牙直播全部看不了，别的平台的正常
**重现步骤**

**截图或视频**
![image](https://github.com/xiaoyaocz/dart_simple_live/assets/74536735/aba3f91b-f950-4726-a3aa-ce981e173ae1)

**平台信息**
 - 设备: iPhone 14pro
 - 系统版本: 17.5.1
 - APP版本:

**Comment by hpkaiq** [comment]
+1

**Comment by rainbow175655** [comment]
我也是

**Comment by KevinllBin** [comment]
同样

**Comment by rikka5201** [comment]
+1，可以获取推荐页，但是关注列表显示未开播，且获取不到视频及弹幕内容

**Comment by reesoon220** [comment]
+1

**Comment by xiaoyaocz** [comment]
已修复，可前往https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9300170437 下载测试版

**Comment by bilibili9331770** [comment]
+1
