### ISSUE TITLE
最新测试版，关注列表 虎牙 开播状态不正常

### ISSUE THREAD

**Issue by hpkaiq** [xiaoyaocz/dart_simple_live#410]
已修复，可前往https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9300170437 下载测试版

_Originally posted by @xiaoyaocz in https://github.com/xiaoyaocz/dart_simple_live/issues/409#issuecomment-2139155520_

**Comment by xiaoyaocz** [comment]
https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9300772179

**Comment by Wenxina** [comment]
> https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9300772179

这个需要在哪下载？怎么没找到apk和ipa文件
