### ISSUE TITLE
[BUG] 关注列表-虎牙主播开播状态异常

### ISSUE THREAD

**Issue by tzjzzzz** [xiaoyaocz/dart_simple_live#411]
**BUG内容**
虎牙播放问题关联的小bug-关注列表-虎牙平台主播不能正常显示开播状态
修复虎牙无法播放问题 #409 #25(https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9300170437)
逍遥神的修复速度真快

**重现步骤**
请在此输入重现步骤
1. 关注用户-列表

**平台信息**
 - APP版本:1.5.4

**Comment by xiaoyaocz** [comment]
#410
