### ISSUE TITLE
Mac 修復

### ISSUE THREAD

**Issue by vick001002** [xiaoyaocz/dart_simple_live#412]
你好想請問最新的虎牙問題mac要如修復 有看到先前的連結說從那裡下載但找不到下載鍵 我是新手 不好意思 求教學

**平台信息** - 裝置：mac - 系統版本：[例如 安卓 10.0] - APP版本：[例如 22]

**Comment by xiaoyaocz** [comment]
![image](https://github.com/xiaoyaocz/dart_simple_live/assets/16559082/d654825d-6342-4f22-a7cb-42a1a88fb080)

如无下载按钮，则可能需要登录Github

**Comment by vick001002** [comment]
> ![image](https://private-user-images.githubusercontent.com/16559082/335219331-d654825d-6342-4f22-a7cb-42a1a88fb080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzkzMjAsIm5iZiI6MTcxNzA3OTAyMCwicGF0aCI6Ii8xNjU1OTA4Mi8zMzUyMTkzMzEtZDY1NDgyNWQtNjM0Mi00ZjIyLWE3Y2ItNDJhMWE4OGZiMDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE0MjM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZTQ5ODQ0ZDk1YmVkZmRhYzY5OTA5ZjYzN2FiYjY5ZGYxZGUxYWFiZWUxM2M1MmU0MTUxYmU5YzVhMDQyMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LrJl4VTXvwtH04NyHssDaG3w7r9s7--FAgUXQbDRMkM)
> 
> 如无下载按钮，则可能需要登录Github

看到了 謝謝大佬即時的解答與修復 ！
