### ISSUE TITLE
[BUG] TV端播放界面菜单无法上下选择

### ISSUE THREAD

**Issue by Sillda** [xiaoyaocz/dart_simple_live#414]
虎牙直播过程中菜单界面能显示出来但无法选择 只要按上下键就切换直播了 希望大佬能看一下是否存在问题 1.0.3的版本是没有问题的
![Uploading IMG_0591.jpeg…]()

 - 设备: [TV]
 - 系统版本: [e.g. Android 10.0]
 - APP版本: [1.0.5]

**Comment by Sillda** [comment]
![Uploading IMG_0591.jpeg…]()

**Comment by xiaoyaocz** [comment]
试试这版本 https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9316500833

**Comment by iyin214** [comment]
> 试试这版本 https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9316500833

还是不行

**Comment by iyin214** [comment]
> 试试这版本 https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9316500833

还是一样的，而且播放一会儿电视会进入息屏屏保状态

**Comment by eason27** [comment]
安装后还是有问题

**Comment by Sillda** [comment]
> 这个版本应该修复了：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9318679662

修复了，这下舒服了，菜单呼出感觉更丝滑了，感谢！！！
