### ISSUE TITLE
[BUG] 抖音直播搜索功能失效

### ISSUE THREAD

**Issue by SinPetec** [xiaoyaocz/dart_simple_live#415]
**截图或视频**
![Screenshot_20240531_192139_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/96854386/6a5acd88-ce51-4b3d-83e7-b3be48ccb1dd)

**平台信息**
 - APP版本: [1.5.5]
 - （修复最新虎牙直播问题版本）

**Comment by xiaoyaocz** [comment]
#379
