### ISSUE TITLE
[BUG] iPadOS 端分享按钮点了没反应

### ISSUE THREAD

**Issue by erdekkfcfy** [xiaoyaocz/dart_simple_live#418]
**BUG内容**
 iPadOS 端分享按钮点了没反应

**平台信息**
 - 设备: ipadair5
 - 系统版本: ipados17.4.1
 - APP版本:

**Comment by xiaoyaocz** [comment]
无法复现。如果无法分享，可以使用”复制链接“功能进行分享。
