### ISSUE TITLE
[BUG] 工具箱链接跳转不了直播间

### ISSUE THREAD

**Issue by wel-come** [xiaoyaocz/dart_simple_live#419]
**BUG内容**
把抖音直播间分享链接输入要

**重现步骤**
把抖音直播间分享链接，输入到工具箱的直播间跳转功能里，点击之后没有反应

**Comment by xiaoyaocz** [comment]
什么版本，什么样的链接

**Comment by wel-come** [comment]
> 什么版本，什么样的链接

啥意思😳

**Comment by xiaoyaocz** [comment]
APP用的什么版本，抖音分享的是什么链接

**Comment by Pizzdd** [comment]
> 什么版本，什么样的链接
借楼问下作者，我有台老ipad2018 用的是12.4.1版本系统
用爱思助手签名了ipa文件后，安装提示设备版本过低。
ipad最低需求版本是多少，还是我操作安装的有问题？
麻烦解答下，谢谢。
也请知道的朋友帮忙说下谢谢

**Comment by xiaoyaocz** [comment]
> > 什么版本，什么样的链接
> > 借楼问下作者，我有台老ipad2018 用的是12.4.1版本系统
> > 用爱思助手签名了ipa文件后，安装提示设备版本过低。
> > ipad最低需求版本是多少，还是我操作安装的有问题？
> > 麻烦解答下，谢谢。
> > 也请知道的朋友帮忙说下谢谢

iOS 13
