### ISSUE TITLE
[BUG] 虎牙直播看不了

### ISSUE THREAD

**Issue by hj52htrrr** [xiaoyaocz/dart_simple_live#421]
**BUG虽然出了测试版，但我确实不知道怎么下载安装。好几天不能看虎牙了，难受

**Comment by w2754946017** [comment]
+1，我也不会安装测试版

**Comment by AllureLoveHJ** [comment]
在md有些测试版在action 点击可以直接跳转。然后下面有不同版本 比如Android 点击后下载 解压即可

**Comment by hj52htrrr** [comment]
> 在md有些测试版在行动点击可以直接跳转。然后下面有不同版本比如安卓点击后下载解压即可

找到了，但是我一不小心把原来的卸载了，数据都没啦，呜呜呜

**Comment by AllureLoveHJ** [comment]
> > 在md有些测试版在行动点击可以直接跳转。然后下面有不同版本比如安卓点击后下载解压即可
> 
> 找到了，但是我一不小心把原来的卸载了，数据都没啦，呜呜呜

哈哈哈 那没办法咯。同时给后来者提醒一下 记得备份数据 因为签名不同（或者有核心破解 可以覆盖安装）

**Comment by luckfalcon** [comment]
> +1，我也不会安装测试版
你需要用电脑登录网页版，然后在action里找最新修复各种bug的版本（这些都是测试版本），然后点开，里面有各个系统的文件下载链接，自己下载对应的系统就好，然后剩下的就是传给手机安装。

**Comment by xiaoyaocz** [comment]
#412
