### ISSUE TITLE
请问测试版1.5.5以后不支持ios14了吗，我的设备点开视频播放界面就闪退

### ISSUE THREAD

**Issue by Zxcx1** [xiaoyaocz/dart_simple_live#422]
**描述**
输入具体的功能描述
【反馈前先查找下是否存在相似的Issues】
【如果你有多个建议、请求，请分开提交Issues】

**附加**
请附加相关截图、视频或链接（好让我知道要我抄哪个APP）

**Comment by xiaoyaocz** [comment]
我这边没法测试iOS 14的情况，按道理是直播的，试试1.6.0。

**Comment by Zxcx1** [comment]
> 我这边没法测试iOS 14的情况，按道理是直播的，试试1.6.0。

重启后一切正常，应该是我自己手机的问题，感谢开发者回复。
