### ISSUE TITLE
[BUG] cpu大核负载异常

### ISSUE THREAD

**Issue by recycle007** [xiaoyaocz/dart_simple_live#425]
### 非重复的Issue

- [x] 已确认没有相似的Issue

### BUG内容

在观看一次直播后返回退出app后热启动app会出现大核负载占满，每次杀掉后台冷启动不会有这个情况。一直以来每个版本都有这个问题

### 重现步骤

```plain text
1、打开app并看一次直播
2、返回退出app再热启动就出现cpu大核负载占满的情况
```

### 截图或视频

![Screenshot_20240603-161455](https://github.com/xiaoyaocz/dart_simple_live/assets/82096497/3eab4c74-c1a4-41fd-8c7c-0eba65c9f280)

### 日志

冷启动和异常热启动日志

### 版本号

1.5.5

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

h2os10

### 设备信息

一加7pro

**Comment by xiaoyaocz** [comment]
CPU调度通常是由底层系统处理的，我也没办法进行相关优化。

**Comment by recycle007** [comment]
> CPU调度通常是由底层系统处理的，我也没办法进行相关优化。

作者你好，最近换了个vivo的平板，发现同样有热启动CPU持续高频的情况，手机是安卓10的一加，平板是安卓14的vivo，不同品牌不同版本的系统都有这个情况啊
