### ISSUE TITLE
[BUG] 魅族手机无法更新应用

### ISSUE THREAD

**Issue by tzjzzzz** [xiaoyaocz/dart_simple_live#428]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

更新版本时提示“安装包无效或不兼容”，但卸载应用后可以正常安装。

### 重现步骤

```plain text
更新版本
```

### 版本号

v8a -1.6 

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

Flyme 10.5.5 安卓14

### 设备信息

meizu 20

### 备注

可能是flyme系统的问题，如果麻烦请🍊作者忽略这个问题（有很好用的数据同步功能）

**Comment by xiaoyaocz** [comment]
上个版本的测试版APK签名有误，如果安装了测试版，可能无法直接升级。建议备份数据后重新安装。
