### ISSUE TITLE
1.6版本，抖音直播最高清晰度只有蓝光，没有原画选项

### ISSUE THREAD

**Issue by SSDYBB** [xiaoyaocz/dart_simple_live#429]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

1.6版本，抖音直播最高清晰度只有蓝光，没有原画选项

### 重现步骤

```plain text
1.6版本，抖音直播最高清晰度只有蓝光，没有原画选项，同一直播间，1.6版本无原画
```

### 截图或视频

![1 5 3](https://github.com/xiaoyaocz/dart_simple_live/assets/40603576/69fb4108-91c3-4254-a158-49e5efd07ed5)
![1 6 0](https://github.com/xiaoyaocz/dart_simple_live/assets/40603576/b720c62b-4e08-4b48-9853-5a2ccf139bb5)

### 版本号

1.6.0

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

11

### 设备信息

11

**Comment by xiaoyaocz** [comment]
测试了下，原画跟蓝光不会同时出现，参数上蓝光跟原画画质实际上是一样的

**Comment by SSDYBB** [comment]
> 测试了下，原画跟蓝光不会同时出现，参数上蓝光跟原画画质实际上是一样的

码率不一样的，放进链接解析获取直链里，蓝光有uhd，原画则没有，码率更高

**Comment by SSDYBB** [comment]
![uhd](https://github.com/xiaoyaocz/dart_simple_live/assets/40603576/87b73bf8-318d-4c7a-86a6-49082f0634a1)
![uhd](https://github.com/xiaoyaocz/dart_simple_live/assets/40603576/fc41ae00-576e-4bf7-8f0b-b572d32c53a4)
![Yh](https://github.com/xiaoyaocz/dart_simple_live/assets/40603576/37f96480-0f9d-416a-a882-0893608903b4)

**Comment by xiaoyaocz** [comment]
直播间链接发一下

**Comment by SSDYBB** [comment]
https://live.douyin.com/121118665759

**Comment by SSDYBB** [comment]
> 直播间链接发一下

https://live.douyin.com/121118665759

**Comment by xiaoyaocz** [comment]
等会试试这版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9399051616
