### ISSUE TITLE
[BUG]抖音关注的主播开播后不显示在线，只能用链接跳转播放

### ISSUE THREAD

**Issue by erdekkfcfy** [xiaoyaocz/dart_simple_live#431]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

已关注的主播开播了，但是刷新后结果不显示
直接进直播间也没用
只能用链接跳转

### 重现步骤

```plain text
上述
```

### 版本号

1.6.0

### 使用版本

正式版(Releases)

### 运行平台

iOS

### 操作系统信息

iPadOS 17.4.1

### 设备信息

Ipadair5

**Comment by erdekkfcfy** [comment]
是之前版本关注的，用新版的抖音搜索重新关注就好了

**Comment by SSDYBB** [comment]
重新关注就好了，但是原画选项没了

**Comment by SUIYUNb** [comment]
一样问题![IMG_20240605_232150.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/168829428/3aafd8b5-55d3-4b10-9c4a-64e899e13365)

![IMG_20240605_232206.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/168829428/877fbc03-b4b4-4541-91c9-5f097625aa46)

明明在直播但是显示没有在直播，重新关注就有两个同样的主播，但只要他下播，下一次他还会显示没有开播![Screenshot_2024-06-05-22-49-36-31_e3cd25cd7d1683da6f376a9c501d0866.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/168829428/48e3dc81-a909-4059-ac67-1e7b46c7f5b1)

![Screenshot_2024-06-05-22-49-40-47_e3cd25cd7d1683da6f376a9c501d0866.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/168829428/9d47a57a-633a-4b54-868d-2f9239b6a113)

![Screenshot_2024-06-05-22-49-57-54_2332cb9b27b851b548ba47a91682926c.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/168829428/7f8752c2-37ea-4330-a144-ba19a1cd2b6f)

![Screenshot_2024-06-05-22-50-05-27_2332cb9b27b851b548ba47a91682926c.jpg](https://github.com/xiaoyaocz/dart_simple_live/assets/168829428/49764a5a-07eb-4af8-8f25-509b72afbade)
点进主页打开应用可以看见这是上一场直播，说明关注的只是那一场直播，只要他下播这个关注就没用了

**Comment by SSDYBB** [comment]
好像因为6.4，抖音全屏看不了弹幕，才会这样

**Comment by xiaoyaocz** [comment]
试试这版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9399051616

**Comment by C2dark** [comment]
windows版的抖音也是，导出关注列表后发现是房间号不对，手动更改房间号后再导入可正常使用
