### ISSUE TITLE
[BUG] windows版本无法安装

### ISSUE THREAD

**Issue by yuf19-2022** [xiaoyaocz/dart_simple_live#434]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

![image](https://github.com/xiaoyaocz/dart_simple_live/assets/109777030/57741497-484d-42e5-b467-df5ce6ab52f8)

### 重现步骤

```plain text
无法安装
```

### 版本号

最新版

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

win11

### 设备信息

win11

**Comment by xiaoyaocz** [comment]
#348
