### ISSUE TITLE
抖音关注的直播不显示正在直播

### ISSUE THREAD

**Issue by cbh198988** [xiaoyaocz/dart_simple_live#435]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

更新最新版本后抖音关注的主播明明在直播，关注列表查看显示未在直播，重新搜索该主播，重新关注后，关注列表显示两个，删除没在直播的，过段时间打开，关注列表抖音的主播又显示没在直播了

### 重现步骤

```plain text
1.打开app关注列表，抖音关注的主播正在直播，关注列表显示没在直播
2.取消关注，重新搜索主播关注
3.过一段时间打开重复出现此bug
```

### 版本号

1.6.0

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

Hyperos 1.0.13.0

### 设备信息

K60Ultra

**Comment by xiaoyaocz** [comment]
#431
