### ISSUE TITLE
[BUG] 最新发布的1.6.3 msix安装无法启动 回退到1.6.0可以启动 

### ISSUE THREAD

**Issue by hzx19980513** [xiaoyaocz/dart_simple_live#437]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

最新编译的1.6.3 msix安装无法启动 回退到1.6.0可以启动 

### 重现步骤

```plain text
msix的1.6.0提示升级 我安装1.6.3之后无法启动
```

### 版本号

1.6.3

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

版本	Windows 10 专业版 版本号	22H2 安装日期	‎2022/‎11/‎7/‎星期一 操作系统内部版本	19045.3930 体验	Windows Feature Experience Pack 1000.19053.1000.0

### 设备信息

Lenovo小新pro16 2021

**Comment by zz-jg** [comment]
+1

**Comment by xiaoyaocz** [comment]
先不要更新吧，或者用zip解压使用。
这个问题很奇怪，明明也没改什么，打包完就跑不起来了。😂

**Comment by hzx19980513** [comment]
> 先不要更新吧，或者用zip解压使用。 这个问题很奇怪，明明也没改什么，打包完就跑不起来了。😂

msix解压了也无法启动 那我暂时先用1.6.0的吧

**Comment by ShAlIow** [comment]
+1

**Comment by xiaoyaocz** [comment]
> > 先不要更新吧，或者用zip解压使用。 这个问题很奇怪，明明也没改什么，打包完就跑不起来了。😂
> 
> 
> 
> msix解压了也无法启动 那我暂时先用1.6.0的吧 

下载zip包解压，不是解压msix包

**Comment by hzx19980513** [comment]
> > > 先不要更新吧，或者用zip解压使用。 这个问题很奇怪，明明也没改什么，打包完就跑不起来了。😂
> > 
> > 
> > msix解压了也无法启动 那我暂时先用1.6.0的吧
> 
> 下载zip包解压，不是解压msix包

我懒 我只用msix的 等你修复更新

**Comment by yangzhiganluzzz** [comment]
> > > 先不要更新吧，或者用zip解压使用。 这个问题很奇怪，明明也没改什么，打包完就跑不起来了。😂
> > 
> > 
> > msix解压了也无法启动 那我暂时先用1.6.0的吧
> 
> 下载zip包解压，不是解压msix包

ZIP也不行

**Comment by xiaoyaocz** [comment]
已重新上传Windows包，重新下载试试
