### ISSUE TITLE
[BUG] 1.6.3WIN版ZIP无法启动

### ISSUE THREAD

**Issue by yangzhiganluzzz** [xiaoyaocz/dart_simple_live#438]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

点启动文件没反应，换回160，正常

### 重现步骤

```plain text
111
```

### 版本号

1.6.3

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

Windows 10 IoT 企业版 LTSC

### 设备信息

AMD Ryzen 7 7840H w/ Radeon 780M Graphics   3.80 GHz

**Comment by xiaoyaocz** [comment]
已重新上传Windows包，重新下载试试
