### ISSUE TITLE
[BUG] 无法获取抖音直播状态

### ISSUE THREAD

**Issue by withered233** [xiaoyaocz/dart_simple_live#440]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

多次更新状态后无法获取抖音直播状态。
类似于[#371](https://github.com/xiaoyaocz/dart_simple_live/issues/371)
不同的是，先前可以获取状态并等待几十秒可以观看。
现版本间隔很长时间后依然无法获取状态。
![S40608-00081430_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/60478611/5a61720e-2cbb-42b4-ad6b-edfb2eabb158)

### 重现步骤

```plain text
　　⁡⁣
```

### 版本号

1.6.3

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

Android13

### 设备信息

meizu

**Comment by xiaoyaocz** [comment]
401/403就是风控了，无解。
只能等一段时间再试或者换个网络。
一直触发这错误的话建议关注少点抖音主播，通过历史记录进去直播间。

**Comment by withered233** [comment]
> 401/403就是风控了，无解。 只能等一段时间再试或者换个网络。 一直触发这错误的话建议关注少点抖音主播，通过历史记录进去直播间。



> 401/403就是风控了，无解。 只能等一段时间再试或者换个网络。 一直触发这错误的话建议关注少点抖音主播，通过历史记录进去直播间。

了解，辛苦开发者。

**Comment by withered233** [comment]
> 401/403就是风控了，无解。 只能等一段时间再试或者换个网络。 一直触发这错误的话建议关注少点抖音主播，通过历史记录进去直播间。

了解，辛苦开发者。
