### ISSUE TITLE
以后会支持电脑网页版吗？

### ISSUE THREAD

**Issue by yangchen158158** [xiaoyaocz/dart_simple_live#442]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

类似，http://live.yj1211.work/index/home/recommend 网页版呢

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
无计划支持网页
