### ISSUE TITLE
Linux建议使用libmpv2

### ISSUE THREAD

**Issue by mymine** [xiaoyaocz/dart_simple_live#445]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

Linux最新发行版的软件库中大多都移除了libmpv1，建议更新使用libmpv2。或者添加调用外部播放器。

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [X] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
需要`media_kit`组件更新，这边无法处理

**Comment by mymine** [comment]
> 需要`media_kit`组件更新，这边无法处理

那能不能调用外部播放器？

**Comment by xiaoyaocz** [comment]
> > 需要`media_kit`组件更新，这边无法处理
> 
> 那能不能调用外部播放器？

使用“链接解析”功能获取直链即可

**Comment by mymine** [comment]
> > > 需要`media_kit`组件更新，这边无法处理
> > 
> > 
> > 那能不能调用外部播放器？
> 
> 使用“链接解析”功能获取直链即可

太麻烦了
