### ISSUE TITLE
越狱环境下，一进直播间就直接卡死

### ISSUE THREAD

**Issue by MML1118** [xiaoyaocz/dart_simple_live#447]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

ipad 系统13.5.1
越狱环境下，一进直播间就直接卡死，非越狱环境下，就能正常观看，求解决

### 重现步骤

```plain text
1.越狱环境下
2.打开直播间
3.直接卡死
```

### 版本号

1.6.3

### 使用版本

正式版(Releases)

### 运行平台

iOS

### 操作系统信息

IOS13.5.1

### 设备信息

iPad Mini 5

**Comment by xiaoyaocz** [comment]
#439 类似
