### ISSUE TITLE
苹果手机发热耗电严重

### ISSUE THREAD

**Issue by s1mple-answer** [xiaoyaocz/dart_simple_live#449]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

苹果手机上发热耗电

### 重现步骤

```plain text
发热耗电严重，不知道是不是没适配高刷的原因，因为打开软件始终120
```

### 版本号

1.6.3

### 使用版本

正式版(Releases)

### 运行平台

iOS

### 操作系统信息

ios15

### 设备信息

iPhone 13 promax

**Comment by xiaoyaocz** [comment]
无法优化，尝试设置里打开/关闭硬解
