### ISSUE TITLE
[BUG]1.6.3版本PC端小窗模式上锁后双击无法最大化窗口

### ISSUE THREAD

**Issue by shenselan** [xiaoyaocz/dart_simple_live#451]
### 非重复的Issue

- [x] 已确认没有相似的Issue

### BUG内容

小窗模式上锁后双击无法最大化窗口，这个功能还是需要的，望找回！

### 重现步骤

```plain text
1：打开任意直播
2：右下角小窗模式
3：点击锁定窗口
4：双击小窗口无法最大化窗口，以前版本可以的！其实做好是双击全屏，而不是最大化窗口！现在连双击最大化窗口也没了！
```

### 版本号

1.6.3

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

Win10

### 设备信息

PC

**Comment by xiaoyaocz** [comment]
正常行为，上锁后将不会响应任何事件
