### ISSUE TITLE
登录虎牙、斗鱼、抖音账号以自动同步各平台关注的主播

### ISSUE THREAD

**Issue by MinCheng7** [xiaoyaocz/dart_simple_live#452]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

各平台关注的主播比较多，一个一个添加有些繁琐。🙏

### 平台

- [X] Android
- [X] iOS
- [X] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
无计划，非必要不会开发登录功能。
