### ISSUE TITLE
抖音弹幕连接失败

### ISSUE THREAD

**Issue by inoyna12** [xiaoyaocz/dart_simple_live#458]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

弹幕连接失败

### 重现步骤

```plain text
任意抖音直播房间
```

### 截图或视频

![Screenshot_2024-06-20-18-11-15-274_com xycz simple_live](https://github.com/xiaoyaocz/dart_simple_live/assets/86736950/40a0f616-6dcc-4c79-b0ea-9936a6d8eefb)

### 版本号

1.6.3

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

android12

### 设备信息

k50

**Comment by xiaoyaocz** [comment]
可暂时使用此测试版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9614675884

**Comment by Though-unachievable** [comment]
![image](https://github.com/xiaoyaocz/dart_simple_live/assets/103250751/1d2ddc13-78c3-4d44-b00f-8148f4c9a27d)
没有windows版本的

**Comment by SSDYBB** [comment]
没有windows版本的

**Comment by xiaoyaocz** [comment]
> 没有windows版本的

https://www.123pan.com/s/PTO8Vv-d3Qyv.html

**Comment by YiDuoCiMei** [comment]
刚好看到

**Comment by YiDuoCiMei** [comment]
> > 没有windows版本的
> 
> https://www.123pan.com/s/PTO8Vv-d3Qyv.html

刚好看到

**Comment by Eila-Shigure** [comment]
> 可暂时使用此测试版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9614675884

测试版本也再次失效了

**Comment by YiDuoCiMei** [comment]
> 可暂时使用此测试版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9614675884

大部分直播间可以，个别直播间需要再次打开，个别直播间不能链接，

我有很多建议，比较多，不是很麻烦问题，比较细节，因为编辑比较麻烦，我准备发送到你邮箱，

**Comment by JZSTAR01** [comment]
> 可暂时使用此测试版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9614675884

好像不是所有直播间都有，有些直播间还是会ws报错

**Comment by CooperHash** [comment]
> 可暂时使用此测试版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9614675884

此测试版本之前可以，现在又挂了

**Comment by kSirZX** [comment]
> > 可暂时使用此测试版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9614675884
> 
> 此测试版本之前可以，现在又挂了

这个测试版本还是无法连接抖音弹幕啊
