### ISSUE TITLE
功能优化

### ISSUE THREAD

**Issue by long1512448773** [xiaoyaocz/dart_simple_live#460]
时隔多年再说一次能否出数据账号同步关注啊！我不想用煞笔虎牙了，广告越来越多，第三代方TV虎牙还掏钱了，真无语了，越来越臃肿，求求你啦，数据账号同步关注的真的太重要了，要不然只能把直播转接链接来这里看了，太让人失望了虎牙😭😭

**Comment by xiaoyaocz** [comment]
无计划
