### ISSUE TITLE
建议添加快手的直播频道

### ISSUE THREAD

**Issue by larmhang** [xiaoyaocz/dart_simple_live#461]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

最近快手投资电竞行业，我平时看的格斗游戏区的街霸以及拳皇主播，基本都被快手买光了，快手平台直播网页版做得很烂，希望大神可以添加一下，哪怕添加一个格斗专区也是可以的，感谢🙏

### 平台

- [X] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [X] Android TV

### 附加信息

快手，例如https://live.kuaishou.com/u/3x55uhvqwfadu32

**Comment by xiaoyaocz** [comment]
暂无计划 #50
