### ISSUE TITLE
TV版抖音搜索修一下吧

### ISSUE THREAD

**Issue by woshishiq1** [xiaoyaocz/dart_simple_live#462]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

修一下抖音搜索tv

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [X] Android TV

**Comment by woshishiq1** [comment]
还有bilibili能不能添加cookie登录,并不想下载biliapp扫码登录

**Comment by xiaoyaocz** [comment]
可先使用此版本：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/9614675884

**Comment by drw2005** [comment]
抖音一直不能搜索。。。

**Comment by woshishiq1** [comment]
不错啊，终于可以ck登录bili了
