### ISSUE TITLE
把IPANDA的链接加里面。没事看看熊猫🐼

### ISSUE THREAD

**Issue by yangzhiganluzzz** [xiaoyaocz/dart_simple_live#468]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

看看熊猫

### 平台

- [X] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
无计划添加新平台支持
