### ISSUE TITLE
[BUG]提示更新1.1.0版本，但是找不到在哪啊。。。

### ISSUE THREAD

**Issue by li5bo5** [xiaoyaocz/dart_simple_live#469]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

提示更新1.1.0版本，但是找不到在哪啊。。。
![image](https://github.com/xiaoyaocz/dart_simple_live/assets/6594141/577a6d6d-b402-4fcc-a1a9-b27151fbb3e1)

### 重现步骤

```plain text
提示更新1.1.0版本，但是找不到在哪啊。。。
```

### 截图或视频

![image](https://github.com/xiaoyaocz/dart_simple_live/assets/6594141/c95808d9-9409-4452-9fc5-160c101a10c4)

### 版本号

TV 1.0.1

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

安卓

### 设备信息

tv

**Comment by xiaoyaocz** [comment]
![image](https://github.com/xiaoyaocz/dart_simple_live/assets/16559082/5eb1bb4b-8958-46b8-9036-0e4470043c1c)

https://github.com/xiaoyaocz/dart_simple_live/releases
