### ISSUE TITLE
求支持电视安卓4.4版

### ISSUE THREAD

**Issue by kokojacket** [xiaoyaocz/dart_simple_live#47]
求支持电视安卓4.4版

**Comment by xiaoyaocz** [comment]
版本太低，无法支持。

**Comment by PaTTeeL** [comment]
同样的情况，家里4个运营商的盒子，全都是4.4的，看着高版本的盒子用能simple live眼馋啊，目前pc版的很好用，看看后续投屏功能加进来后能不能实现曲线救国了！
