### ISSUE TITLE
[Feature] 双开/多开软件/直播间

### ISSUE THREAD

**Issue by fuyn101** [xiaoyaocz/dart_simple_live#474]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

如果本意是可以双开，那这是个bug
![image](https://github.com/xiaoyaocz/dart_simple_live/assets/151902446/00b81027-e1d9-4f87-a90c-b157ff92b2e4)

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

### 附加信息

没找到现成的软件形式

**Comment by xiaoyaocz** [comment]
Flutter不支持多窗口
