### ISSUE TITLE
[BUG] Windows 版本 1.6.3版本 抖音直播聊天信息显示错误

### ISSUE THREAD

**Issue by qiangli999** [xiaoyaocz/dart_simple_live#477]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

Windows 版本 1.6.3版本 抖音直播聊天信息显示错误

### 重现步骤

```plain text
每次都是同样BUG
```

### 截图或视频

![20240714124532](https://github.com/user-attachments/assets/3d78eefd-e98a-40f8-aa1d-27ee6d17236f)

### 版本号

1.6.3

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

windows10

### 设备信息

PC

**Comment by xiaoyaocz** [comment]
#458
