### ISSUE TITLE
多开以及小窗置顶的问题

### ISSUE THREAD

**Issue by rxsmmxs** [xiaoyaocz/dart_simple_live#479]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

首先！表示感谢！其次，一个是不知道是不是我这边单独的问题，就是小窗下，强制置顶，其次就是，希望多开直播间能整出来，然后小窗的尺寸匹配，希望能做好。感谢开发者！

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
flutter不支持多窗口。小窗默认就是强制置顶。
