### ISSUE TITLE
pc端抖音直播

### ISSUE THREAD

**Issue by rxsmmxs** [xiaoyaocz/dart_simple_live#484]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

pc端看抖音直播，某些直播该直播类型或玩法电脑端暂未支持（大部分是支持连麦的），但是前几天这种类型的直播通过直播间跳转能打开，这两天又不行了。

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
可能是抖音限制了，抖音Web端不支持的支持不了
