### ISSUE TITLE
[BUG] 斗鱼分类显示错误

### ISSUE THREAD

**Issue by Hokmanz** [xiaoyaocz/dart_simple_live#485]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

不显示分类图标，只有文字。

### 重现步骤

```plain text
打开软件，斗鱼分类不显示ui
```

### 截图或视频

![Screenshot_2024-07-23-21-08-37-007](https://github.com/user-attachments/assets/c86aec43-2f38-423d-a45a-8c7b7eee87d5)

### 版本号

1.6.5

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

Android12

### 设备信息

Redmagic NX709S

**Comment by lirenxd** [comment]
tv版本1.1.2也错误了

**Comment by xiaoyaocz** [comment]
已修复，可下载开发版： https://github.com/xiaoyaocz/dart_simple_live/actions/runs/10087359175

**Comment by hpkaiq** [comment]
> 已修复，可下载开发版： https://github.com/xiaoyaocz/dart_simple_live/actions/runs/10087359175

这个版本无法打开
