### ISSUE TITLE
[Feature] 建议增加各个直播平台的登录，发送弹幕功能

### ISSUE THREAD

**Issue by ilsaay** [xiaoyaocz/dart_simple_live#487]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

建议增加各个直播平台的登录，发送弹幕功能

### 平台

- [X] Android
- [X] iOS
- [X] MacOS
- [X] Windows
- [X] Linux
- [X] Android TV

**Comment by xiaoyaocz** [comment]
无计划，非必要不会开发登录功能。
