### ISSUE TITLE
[BUG] 哔哩哔哩直播 no such meth error

### ISSUE THREAD

**Issue by gaoyintai** [xiaoyaocz/dart_simple_live#490]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

bilibili进直播间显示 **no such meth error**
**安卓** **ios** 都是同样的问题

### 重现步骤

```plain text
哔哩哔哩直播
```

### 截图或视频

![Screenshot_2024-08-06-18-36-12-853_com xycz simple_live](https://github.com/user-attachments/assets/adc32155-3bbc-4398-a318-b14c2c42f891)

### 版本号

ver.1.6.5

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

ios

### 设备信息

ios

**Comment by luckygaogaogao** [comment]
*谢谢大佬
