### ISSUE TITLE
[BUG] 最新的1.6.9版本字体变细了

### ISSUE THREAD

**Issue by anjinga** [xiaoyaocz/dart_simple_live#491]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

最新版字体变得很细，看起来很别扭，好像没有调用到系统字体，上一个1.6.8版本是正常的

### 重现步骤

```plain text
打开app即可看到字体变细
```

### 版本号

1.6.9

### 使用版本

开发版(Actions)

### 运行平台

Android

### 操作系统信息

coloros14

### 设备信息

oneplus12

**Comment by a254476321** [comment]
听说是webview新版的问题

**Comment by xiaoyaocz** [comment]
回滚Flutter 3.22了，3.24应该有问题
