### ISSUE TITLE
[BUG] Win版启动白屏

### ISSUE THREAD

**Issue by rikka5201** [xiaoyaocz/dart_simple_live#494]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

启动白屏，重启无法解决

### 重现步骤

```plain text
1.刚覆盖更新后可以启动
2.后来启动白屏
（修改过自动更新时间为5分钟，不知是否有影响）
```

### 版本号

1.7.2

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

windows 11 23h2

### 设备信息

PC

**Comment by rikka5201** [comment]
![image](https://github.com/user-attachments/assets/d4e71b32-a3b9-43b0-986b-d1f641b1fd8c)

**Comment by rikka5201** [comment]
![屏幕截图 2024-08-13 191418](https://github.com/user-attachments/assets/74e713dc-1bac-4be1-9df0-9234f15d2b37)

**Comment by Wangzifu98** [comment]
白屏大概是因为你开了两个 
![image](https://github.com/user-attachments/assets/95d2fdee-9231-47ae-83fb-a5c6417f61fb)

**Comment by rikka5201** [comment]
我知道开两个会白屏，但是只开了一个
![屏幕截图 2024-08-13 193841](https://github.com/user-attachments/assets/78d4ab0b-2b25-434a-860b-41992524ae24)

**Comment by xiaoyaocz** [comment]
更新1.7.3
