### ISSUE TITLE
[BUG] 新版安卓端出现白屏无法恢复

### ISSUE THREAD

**Issue by xc0128** [xiaoyaocz/dart_simple_live#496]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

第一次打开新版时调整了新增的自动更新的线程数4调到1，接着加载关注就软件就卡住了，然后重新启动就是白屏无法操作，后面重复启动就是卡在白屏页面无法恢复

### 重现步骤

```plain text
1.打开设置新增的自动更新进入
2.里面的线程数4调到1，其他设置默认没有更改
3.加载关注软件卡住没有反应
4.关掉重启白屏无法操作
5.一直重启仍然卡在白屏界面无法恢复
```

### 截图或视频

![Screenshot_2024-08-13-19-58-22-84_e3cd25cd7d1683da6f376a9c501d0866](https://github.com/user-attachments/assets/b12038d4-fff4-46dc-9782-8b7e00073e12)

### 版本号

1.72

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

realme UI 3.0  Android12

### 设备信息

realme X7 Pro

### 备注

白屏后清理了应用缓存

**Comment by xiaoyaocz** [comment]
更新1.7.3
