### ISSUE TITLE
希望加上只听声音的功能

### ISSUE THREAD

**Issue by huangwenen** [xiaoyaocz/dart_simple_live#499]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

因为很多人都是挂着在直播间听歌，或者听主播逼逼赖赖的，所以并不需要看视频。希望加上后台播放只听声音类似的功能，那就可以减少很大一部分流量，对于我这种流量昂贵地方的实在太有用了。。。我记得斗鱼APP有这个功能的，但是B站没有

### 平台

- [X] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
#471
