### ISSUE TITLE
[Feature] 希望关注页能显示直播标题和封面

### ISSUE THREAD

**Issue by TempaleSans** [xiaoyaocz/dart_simple_live#504]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

有的主播播某些游戏时才会点进去看，如果关注页就能显示标题和封面就更方便了

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [X] Android TV

**Comment by xiaoyaocz** [comment]
#128
