### ISSUE TITLE
[BUG] Altstore无法签名1.7.3

### ISSUE THREAD

**Issue by MaxTop9** [xiaoyaocz/dart_simple_live#505]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(1368): _assert(): end >= size - 0x10

### 重现步骤

```plain text
无法签名
```

### 截图或视频

![IMG_5929](https://github.com/user-attachments/assets/855d1297-3b33-4381-889d-33f7f6ade53d)

### 版本号

1.7.3

### 使用版本

正式版(Releases)

### 运行平台

iOS

### 操作系统信息

ios17.5.1

### 设备信息

IPhone 12 Promax

### 备注

无法签名，尝试了1.6.4test版能用

**Comment by xiaoyaocz** [comment]
无法解决，建议换个侧载方式
https://github.com/altstoreio/AltStore/issues/1034
