### ISSUE TITLE
[Feature] 请求增加开播提醒功能

### ISSUE THREAD

**Issue by Glitter-0** [xiaoyaocz/dart_simple_live#508]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

关注的主播开播后能否发出通知提醒？

### 平台

- [X] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
做不到开播提醒，程序需要常驻后台去读取状态非常耗费资源，且APP未接入任何推送
