### ISSUE TITLE
陀螺仪陀螺仪

### ISSUE THREAD

**Issue by woshishiq1** [xiaoyaocz/dart_simple_live#511]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

啥时候能添加陀螺仪，全盘模式下随手机翻转转动画面啊，没有这个，只能开启系统的自动旋转功能。好不方便

### 平台

- [X] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
#250
