### ISSUE TITLE
请求添加个后台小窗播放

### ISSUE THREAD

**Issue by QiuSheng1998** [xiaoyaocz/dart_simple_live#517]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

请求添加后台小窗播放 ，谢谢

### 平台

- [X] Android
- [X] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by QiuSheng1998** [comment]
安卓好像已经有了 就iOS现在没有

**Comment by xiaoyaocz** [comment]
ios需要上游播放组件支持，现在还做不到。
#13
