### ISSUE TITLE
斗鱼无法观看，抖音能看出现服务器连接失败

### ISSUE THREAD

**Issue by rianjskis** [xiaoyaocz/dart_simple_live#518]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

请修复

### 重现步骤

```plain text
‘’
```

### 版本号

安卓 1.7.3

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

安卓14

### 设备信息

一加ace3

**Comment by xiaoyaocz** [comment]
抖音已恢复。都要测试无问题。
