### ISSUE TITLE
[手势切屏] 增加类似抖音那样的快捷手势在全屏观看下进行直播切换。两种模式：1.选择收藏列表，只切换收藏列表里面的直播。2.默认随机切换。切换方式：1.上下滑动手势。2.长按手势。

### ISSUE THREAD

**Issue by hai9740** [xiaoyaocz/dart_simple_live#522]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

1.1 

### 平台

- [X] Android
- [X] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
无计划开发此功能
