### ISSUE TITLE
抖音直播全部错误[BUG] 请填写简短易读的标题

### ISSUE THREAD

**Issue by tkl11** [xiaoyaocz/dart_simple_live#523]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

抖音直播全部无法播放，显示错误代码
![Screenshot_20240926_152152_com xycz simple_live](https://github.com/user-attachments/assets/3e433698-4276-460b-bc20-18740b9c2cc9)

### 重现步骤

```plain text
抖音直播错误代码
```

### 截图或视频

![Screenshot_20240926_152152_com xycz simple_live](https://github.com/user-attachments/assets/1371cebb-a66d-41ad-b0dc-d5e3824bb4f2)

### 版本号

1.7.3

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

荣耀30s

### 设备信息

30s

**Comment by xiaoyaocz** [comment]
抖音风控无法解决，等一段时间再试或尝试更换网络环境。
