### ISSUE TITLE
flutter_inappwebview 6.1.0 with InAppWebView widget macOS and Windows support

### ISSUE THREAD

**Issue by pichillilorenzo** [xiaoyaocz/dart_simple_live#525]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

Hello @xiaoyaocz, I'm the author of the [flutter_inappwebview](https://github.com/pichillilorenzo/flutter_inappwebview/) Flutter plugin and I found out that your project is using it!
I recently updated the plugin with InAppWebView widget macOS and Windows support!

I would really like to add your project to the [Showcase](https://inappwebview.dev/showcase) page of the official plugin website.
It shows an open list of apps built with Flutter InAppWebView (both open and closed source).

So, may I have your permission to add it there?
If yes, I would like to have just a simple description of what `flutter_inappwebview` plugin was used for, and for which feature in your app.
For the screenshots and app logo, maybe, I could use the ones you have in your repository or on the app stores.

Hope to receive a positive feedback, thanks a lot!

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
I'm very honored to have my project added to the Showcase page. 
However, this project only uses flutter_inappwebview on the login page, so there might not be much to showcase😂.

**Comment by pichillilorenzo** [comment]
No problem, thanks!
