### ISSUE TITLE
[BUG] 聚合直播UWP看直播卡顿

### ISSUE THREAD

**Issue by ColdTearsYY** [xiaoyaocz/dart_simple_live#527]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

搜到类似的问题反馈：
![image](https://github.com/user-attachments/assets/d42556af-b8bb-4913-a5d3-a406323dc11a)
聚合直播UWP看抖音卡顿

### 重现步骤

```plain text
1.打开UWP
2.打开一个抖音直播间
3.画面卡顿
（最近出现的问题，在几周前没有）
```

### 版本号

2.1.7

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

Windows 10 22H2

### 设备信息

pc

**Comment by xiaoyaocz** [comment]
如果是最近出现的，看看是否是更新了系统、显卡驱动导致的。
聚合直播到这里反馈：https://github.com/xiaoyaocz/AllLive/issues
