### ISSUE TITLE
[Feature] 关注列表能否显示当前直播标题或者画面

### ISSUE THREAD

**Issue by bing996** [xiaoyaocz/dart_simple_live#530]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

因为看直播剧比较多,关注列表只显示up名字,  看不到正在直播的内容.

### 平台

- [X] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
#128
