### ISSUE TITLE
PC端Bilibili账号的关注列表不会出现

### ISSUE THREAD

**Issue by SXK445221** [xiaoyaocz/dart_simple_live#531]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

<img width="1280" alt="Snipaste_2024-10-10_22-13-02" src="https://github.com/user-attachments/assets/06e7c6b7-522e-4c1c-b744-1bdf508c054e">

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

### 附加信息

[simple_live_app-1.7.3+10703-windows.zip](https://github.com/xiaoyaocz/dart_simple_live/releases/download/v1.7.3/simple_live_app-1.7.3+10703-windows.zip)

**Comment by xiaoyaocz** [comment]
登录只是可以看高清直播，并不会同步关注列表
