### ISSUE TITLE
请问下有开发鸿蒙next版本的打算吗

### ISSUE THREAD

**Issue by LaffeyLa** [xiaoyaocz/dart_simple_live#533]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

请问下有开发鸿蒙next版本的打算吗

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
开发中
