### ISSUE TITLE
Windows 字体问题

### ISSUE THREAD

**Issue by omgcao** [xiaoyaocz/dart_simple_live#535]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

- 系统： Windows 10 企业版 1809  17763.6414
- 软件：dart simple live  1.7.3
- 问题：看起来软件优先调了日文字体，显示效果查看截图中的“关”字。
- Windows 11 也有此类问题

**截图**
![2](https://github.com/user-attachments/assets/6a3b24d2-d8b7-4748-8ce2-d5876a1fa1ac)
![1](https://github.com/user-attachments/assets/f22875b9-3714-4ee5-abf8-9acf868887ca)

### 重现步骤

```plain text
一直存在，未发现软件内更改字体选项。
```

### 版本号

1.7.3

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

Windows 10 企业版 1809  17763.6414

### 设备信息

Windows 台式电脑

**Comment by omgcao** [comment]
补充一张图，看起来是较常见字体配置文件问题
![image](https://github.com/user-attachments/assets/47b1bc8c-dd0b-42fb-8178-e18ea8420219)

**Comment by fufumo** [comment]
我也觉得字体怪怪的，不知道咋替换字体

**Comment by fufumo** [comment]
我也觉得字体怪怪的，不知道咋替换字体

**Comment by xiaoyaocz** [comment]
更新[1.7.4](https://github.com/xiaoyaocz/dart_simple_live/releases)
