### ISSUE TITLE
[Feature] 将请求地址由"http://" 发出请求前全部替换为"https://"

### ISSUE THREAD

**Issue by augumn** [xiaoyaocz/dart_simple_live#538]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

在公司网络环境下, 不知道运维在网关层面做了什么设置, 导致simple_live不能播放视频, 但是在网页上打开抖音是能正常看直播的. chrome现在是强制https的.

在另外一个抖音录制的python项目中, 抖音也是不能直接录制的, 但是我修改了下url的逻辑之后就可以正常录制的, dart我不熟, 大概率也是同理的.

从各个视频平台的某个接口获取到视频地址后替换为https

```python
        if str(m3u8_url).startswith("http://"):
            m3u8_url = m3u8_url.replace("http://", "https://")
        if str(flv_url).startswith("http://"):
            flv_url = flv_url.replace("http://", "https://")
```

### 平台

- [X] Android
- [X] iOS
- [X] MacOS
- [X] Windows
- [X] Linux
- [X] Android TV

**Comment by xiaoyaocz** [comment]
更新[1.7.4](https://github.com/xiaoyaocz/dart_simple_live/releases)
