### ISSUE TITLE
加个快手可以吗

### ISSUE THREAD

**Issue by GUG001** [xiaoyaocz/dart_simple_live#539]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

我需要快手平台

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

### 附加信息

快手的直播

**Comment by xiaoyaocz** [comment]
无计划添加新平台
