### ISSUE TITLE
小窗播放优化，太小了看不清

### ISSUE THREAD

**Issue by tkl11** [xiaoyaocz/dart_simple_live#540]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

可以优化一下小窗播放吗，实在太小了，最好竖屏宽度，或者可以自行拉伸，急需

### 平台

- [X] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

### 附加信息

就类似斗鱼虎牙小窗就可以

**Comment by xiaoyaocz** [comment]
小窗大小是系统决定的。你可以试试双指放大小窗。
