### ISSUE TITLE
[Feature] 播放中断后取消保持亮屏

### ISSUE THREAD

**Issue by WindFlames** [xiaoyaocz/dart_simple_live#541]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

软件禁止了手机的自动熄屏功能，在直播卡死，下播等无法正常播放时建议恢复自动熄屏的功能。这样在看直播睡着时不至于让手机一直亮屏，容易烧屏。

### 平台

- [X] Android
- [ ] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
更新[1.7.4](https://github.com/xiaoyaocz/dart_simple_live/releases)
