### ISSUE TITLE
[BUG] 虎牙一起看播放中断

### ISSUE THREAD

**Issue by LaoYuan77** [xiaoyaocz/dart_simple_live#543]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

最近在simple live 看虎牙直播电视剧的时候，经常看着看着就突然黑屏，然后弹出以下内容，就在发这段消息的时候，软件又突然黑屏了。

### 重现步骤

```plain text
正常观看虎牙直播，随机出现黑屏，无法播放现象，刷新之后，又会随机出现黑屏无法播放现象。
```

### 截图或视频

![QQ图片20241112214559](https://github.com/user-attachments/assets/b9d80e1b-505a-4ee6-8372-48f54910b134)

### 版本号

1.7.3

### 使用版本

正式版(Releases)

### 运行平台

iOS

### 操作系统信息

iPhone 12 Pro Max iOS 14.3

### 设备信息

iPhone 12 Pro Max iOS 14.3

**Comment by WOJIAOSHIYI** [comment]
加1

**Comment by s411905117** [comment]
+1

**Comment by tungcss** [comment]
+1

**Comment by i25net** [comment]
一起看栏目
作者用的虎牙小程序接口，源码里看到的，
而小程序目前获取到的flv断流很频繁，基本上1分钟左右就断流。

用pc端接口稳定些

**Comment by yaoyuhang0727** [comment]
windows端也是一样。1到2分钟就直接断流。。。不知道什么时候会修复啊。。好难受。。。

**Comment by xsw979** [comment]
我也是

**Comment by i25net** [comment]
> windows端也是一样。1到2分钟就直接断流。。。不知道什么时候会修复啊。。好难受。。。


非常感谢作者的辛勤付出，整合了多平台的直播源
我在友善的肥羊的交流群，看到的说web端的接口稳定些，并不是指pc客户端
作者参考的几个开源项目里没有肥羊的项目，因为肥羊闭源了，我也是fork了别人fork的历史项目参考。
作者有兴趣的话可以与肥羊联系探讨解决修复方案

**Comment by xiaoyaocz** [comment]
更新[1.7.4](https://github.com/xiaoyaocz/dart_simple_live/releases)

**Comment by eason27** [comment]
TV端更新后虎牙原来能看的现在不能看了

**Comment by yaoyuhang0727** [comment]
更新了最新以后，一起看还是会断流。。。。。

**Comment by alilialic** [comment]
更新的前两个小时是没断流的，之后又断流了...

**Comment by yaoyuhang0727** [comment]
> 更新了最新以后，一起看还是会断流。。。。。

好像好一点了？

**Comment by yaoyuhang0727** [comment]
> > 更新了最新以后，一起看还是会断流。。。。。
> 
> 好像好一点了？

刚说完就G了。。。。。

**Comment by mymine** [comment]
> ~更新[1.7.4](https://github.com/xiaoyaocz/dart_simple_live/releases)~

虎牙又断流了。

**Comment by xsw979** [comment]
是的看来1.7.4的更新并未彻底解决虎牙一起看板块断流问题
