### ISSUE TITLE
[Feature] 电脑端能否加一个录制视频直播的功能

### ISSUE THREAD

**Issue by blblank** [xiaoyaocz/dart_simple_live#547]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

电脑端能否加一个录制视频直播的功能

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
无计划开发录播功能。
