### ISSUE TITLE
[BUG] 抖音直播无弹幕

### ISSUE THREAD

**Issue by JZSTAR01** [xiaoyaocz/dart_simple_live#550]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

直播内容正常，显示弹幕服务器连接正常但是没有弹幕

### 重现步骤

```plain text
111
```

### 版本号

最新

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

鸿蒙4

### 设备信息

Huawei Matepad 11 2021

**Comment by xiaoyaocz** [comment]
无法复现。有可能是你的网络环境触发抖音风控，尝试换个网络环境。
