### ISSUE TITLE
[Feature] 希望能添加 快手平台

### ISSUE THREAD

**Issue by blblank** [xiaoyaocz/dart_simple_live#551]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

希望能添加 快手平台

### 平台

- [X] Android
- [X] iOS
- [X] MacOS
- [X] Windows
- [X] Linux
- [X] Android TV

**Comment by waahah** [comment]
同样+1

**Comment by xiaoyaocz** [comment]
无计划添加新平台支持。
