### ISSUE TITLE
[Feature] 使用AltServer安装的时候报错了

### ISSUE THREAD

**Issue by ImJING** [xiaoyaocz/dart_simple_live#552]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

使用AltServer安装的时候报错了
安装其他ipa正常的，没超过3个限制
ldid.cpp(1461): _assert(): end >= size - 0x10
![微信图片_20241122234052](https://github.com/user-attachments/assets/dfbd4d8a-0452-4d3a-a5b9-befebb6a6dd6)

### 平台

- [ ] Android
- [X] iOS
- [ ] MacOS
- [ ] Windows
- [ ] Linux
- [ ] Android TV

**Comment by feiwubill** [comment]
我这遇到同样的问题

**Comment by xiaoyaocz** [comment]
无法解决，建议换个侧载方式
#505
