### ISSUE TITLE
有没有可能结合这个软件自动录播上传https://github.com/biliup/biliup

### ISSUE THREAD

**Issue by DifferentSparkler** [xiaoyaocz/dart_simple_live#554]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

录制各大主流直播平台并上传至哔哩哔哩弹幕网
自动选择上传线路，保证上传稳定性，可手动调整并发
支持录制哔哩哔哩、斗鱼、虎牙、Twitch直播弹幕用于外挂播放器
防止录制花屏（使用默认的stream-gears下载器就会有这个功能），解决网络、PK导致的花屏。
[更新日志 »](https://biliup.github.io/biliup/docs/guide/changelog)

### 平台

- [X] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

### 附加信息

录制各大主流直播平台并上传至哔哩哔哩弹幕网
自动选择上传线路，保证上传稳定性，可手动调整并发
支持录制哔哩哔哩、斗鱼、虎牙、Twitch直播弹幕用于外挂播放器
防止录制花屏（使用默认的stream-gears下载器就会有这个功能），解决网络、PK导致的花屏。
[更新日志 »](https://biliup.github.io/biliup/docs/guide/changelog)

**Comment by xiaoyaocz** [comment]
无计划开发录播功能，建议使用其他录播软件。
