### ISSUE TITLE
[Feature]  win版本直播，能否增加多标签模式，一次性看十几个直播，切换的看。

### ISSUE THREAD

**Issue by yangchen158158** [xiaoyaocz/dart_simple_live#555]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

win版本的直播，能否增加多标签模式（网页版 都是习惯这样），一次性看十几个直播，切换的看。

### 平台

- [ ] Android
- [ ] iOS
- [ ] MacOS
- [X] Windows
- [ ] Linux
- [ ] Android TV

**Comment by xiaoyaocz** [comment]
无计划开发此功能。
建议下载[聚合直播](https://apps.microsoft.com/detail/9n1twg2g84vd?hl=zh-cn&gl=CN)，并开启「新窗口播放」。
