### ISSUE TITLE
[BUG] Android TV 1.2.0

### ISSUE THREAD

**Issue by sillda76** [xiaoyaocz/dart_simple_live#557]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

虎牙直播无法正常播放，其他平台正常

### 重现步骤

```plain text
播放两秒就自动跳到下一个线路，然后重现，直到播放失败
```

### 版本号

TV 1.2.0

### 使用版本

开发版(Actions)

### 运行平台

Android TV

### 操作系统信息

Android TV

### 设备信息

TV 1.2.0

**Comment by xiaoyaocz** [comment]
更新1.2.1：https://github.com/xiaoyaocz/dart_simple_live/releases/tag/tv_v1.2.1
