### ISSUE TITLE
[BUG] 虎牙弹幕服务器连接失败

### ISSUE THREAD

**Issue by ShimaRain** [xiaoyaocz/dart_simple_live#562]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

虎牙直播间连接不上弹幕服务器，能播放但没有弹幕，提示：服务器连接失败WebSocketChannelException：HandshakeException: Connection terminated during
handshake
或者提示：服务器连接失败WebSocketChannelException：
HandshakeException: Connection terminated during
handshake
近期直播画面也时不时黑屏转圈反复自动换线路仍黑屏

### 重现步骤

```plain text
不是必定复现但是今天碰见多次，网络没问题，关闭代理软件也连不上弹幕服务器
```

### 截图或视频

![94B21A27-6F00-4E76-8BB5-8DFFE2552141](https://github.com/user-attachments/assets/3da1559c-4db4-40f1-9b4b-4372a7ce07fe)

### 日志

[2024-12-05 15-24-03.log](https://github.com/user-attachments/files/18019091/2024-12-05.15-24-03.log)
[2024-12-05 15-24-36.log](https://github.com/user-attachments/files/18019093/2024-12-05.15-24-36.log)

### 版本号

1.7.5

### 使用版本

正式版(Releases)

### 运行平台

iOS

### 操作系统信息

iOS15.4.1

### 设备信息

iPhone13Pro

**Comment by xiaoyaocz** [comment]
无法复现。看报错应该就是你的网络有问题

**Comment by ShimaRain** [comment]
降级1.7.3就一切正常

**Comment by xiaoyaocz** [comment]
近期版本并未修改弹幕相关代码
