### ISSUE TITLE
Add English language 

### ISSUE THREAD

**Issue by snehith0269dev** [xiaoyaocz/dart_simple_live#563]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### 功能描述

Please MIG 2B 50, Simhapuri colony, simhachalam English language support to the app 

### 平台

- [X] Android
- [X] iOS
- [X] MacOS
- [X] Windows
- [X] Linux
- [X] Android TV

**Comment by xiaoyaocz** [comment]
No plans at the moment.
