### ISSUE TITLE
[BUG] 进入直播间卡死，无法加载直播，也无法退出app

### ISSUE THREAD

**Issue by TajangSec** [xiaoyaocz/dart_simple_live#564]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

最新1.7.5版本。安卓v8a那个。中兴手机，系统是myos
今天打开直播间，转了一会圈，然后卡死，返回键，锁屏键，通知栏等等全部失效。长按锁屏15秒才重启手机

### 重现步骤

```plain text
任意一个关注列表里的哔哩哔哩直播间
日志文件，没有当时卡死的日志，我是看了issue才打开日志的。但是我复现时仍然出现了严重的卡顿。手机无法退出app
```

### 日志

[日志.zip](https://github.com/user-attachments/files/18057872/default.zip)

### 版本号

1.7.5

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

MyOS13.0.29_A2023P   Android 13

### 设备信息

中兴Axon40 Ultra

**Comment by xiaoyaocz** [comment]
尝试以下步骤：
1. 直播设置中打开/关闭兼容模式，硬件解码
2. 关注设置中将 更新线程数 设置为1

**Comment by TajangSec** [comment]
> 尝试以下步骤：
> 
> 1. 直播设置中打开/关闭兼容模式，硬件解码
> 2. 关注设置中将 更新线程数 设置为1

可以了
