### ISSUE TITLE
[BUG] 电视端看2k卡顿

### ISSUE THREAD

**Issue by DecCapri** [xiaoyaocz/dart_simple_live#569]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

电视上看2k直播会有卡顿掉帧现象，开启兼容模式后问题消失，但别的直播间会黑屏，只有声音

### 重现步骤

```plain text
电视上看2k直播会有卡顿掉帧现象
```

### 版本号

tv1.2.2

### 使用版本

正式版(Releases)

### 运行平台

Android

### 操作系统信息

android9

### 设备信息

tv

**Comment by xiaoyaocz** [comment]
非原生应用，解决不了性能问题。
可以尝试设置中打开兼容模式。

**Comment by DecCapri** [comment]
> 非原生应用，解决不了性能问题。 可以尝试设置中打开兼容模式。

开兼容模式原本正常的直播间出现了黑屏但有声音的现象
