### ISSUE TITLE
[BUG] 小米电视安装不了Tv版

### ISSUE THREAD

**Issue by ChenpiTailang** [xiaoyaocz/dart_simple_live#570]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

小米电视安装不了Tv版

### 重现步骤

```plain text
小米电视安装不了Tv版
```

### 版本号

1.2.2

### 使用版本

正式版(Releases)

### 运行平台

Android TV

### 操作系统信息

Android 12

### 设备信息

小米TV

**Comment by xiaoyaocz** [comment]
检查有没有下载对架构

**Comment by ChenpiTailang** [comment]
[TV 1.2.2](https://github.com/xiaoyaocz/dart_simple_live/releases/tag/tv_v1.2.2)在这里面下载的
