### ISSUE TITLE
[BUG] 抖音弹幕服务器挂了，安卓手机和tv版都看不了弹幕

### ISSUE THREAD

**Issue by Laoyutuo** [xiaoyaocz/dart_simple_live#571]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

弹幕没有

### 重现步骤

```plain text
没有弹幕
```

### 版本号

1.2.2

### 使用版本

正式版(Releases)

### 运行平台

Android TV

### 操作系统信息

Android 

### 设备信息

小米电视

**Comment by inoyna12** [comment]
+1

**Comment by 12586676** [comment]
+1

**Comment by besmart1874** [comment]
+1

**Comment by xxmyxz** [comment]
1.7.5版本   +1

**Comment by PokersKun** [comment]
临时解决抖音弹幕的版本可以从我的Action里下载：

**Comment by inoyna12** [comment]
又能看到弹幕了，不需要修复了。

**Comment by skyyy123105** [comment]
可以看到啦！辛苦了

**Comment by NeverHaving** [comment]
这是啥情况，现在又能看到了，有大佬能解释一下吗？

**Comment by xiaoyaocz** [comment]
证书过期，已更新
