### ISSUE TITLE
[BUG] win10专业版无法看抖音

### ISSUE THREAD

**Issue by a2295875** [xiaoyaocz/dart_simple_live#577]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

直播平台：抖音直播
房间号：163823390463
错误信息：
发送HEAD请求失败
----------------
#0      HttpClient.head (package:simple_live_core/src/common/http_client.dart:160)
<asynchronous suspension>
#1      DouyinSite._getWebCookie (package:simple_live_core/src/douyin_site.dart:365)
<asynchronous suspension>
#2      DouyinSite._getRoomDataByHtml (package:simple_live_core/src/douyin_site.dart:388)
<asynchronous suspension>
#3      DouyinSite._getRoomDetailByWebRidHtml (package:simple_live_core/src/douyin_site.dart:310)
<asynchronous suspension>
#4      DouyinSite.getRoomDetailByWebRid (package:simple_live_core/src/douyin_site.dart:255)
<asynchronous suspension>
#5      DouyinSite.getRoomDetail (package:simple_live_core/src/douyin_site.dart:185)
<asynchronous suspension>
#6      LiveRoomController.loadData (package:simple_live_app/modules/live_room/live_room_controller.dart:280)
<asynchronous suspension>

### 重现步骤

```plain text
无法加载抖音直播
```

### 版本号

1.7.5

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

版本	Windows 10 专业版 版本号	21H2 

### 设备信息

PC

**Comment by xiaoyaocz** [comment]
抖音风控，无解。
等待一段时间再试或换个网络环境。
