### ISSUE TITLE
竖屏的直播（比如抖音）在自动全屏后会变成横屏

### ISSUE THREAD

**Issue by anjinga** [xiaoyaocz/dart_simple_live#73]
感谢作者的更新
如题，竖屏的直播（比如抖音）在自动全屏后会变成横屏然后中间显示一小块
另外可否在自动全屏后过几秒钟隐藏四周的控制栏
谢谢

**Comment by kriovo** [comment]
1.是否可以恢复后台播放 有时候只想听声音 上个版本可以更新之后就不可以
2.是否可以增加直播平台排序自定义 平时看虎牙比较多 哔哩哔哩看的少
3.虎牙偶现分类图片加载不出来 如果出现这种情况 点分类不会是该分类的内容
![Screenshot_20230803_174853](https://github.com/xiaoyaocz/dart_simple_live/assets/137449163/29030bf5-8d86-4bfe-ad5c-423895dfd7f2)
![Screenshot_20230803_175026](https://github.com/xiaoyaocz/dart_simple_live/assets/137449163/c0949b2e-4909-4322-81a0-7a0dc2b29642)
