### ISSUE TITLE
新发布的1.2.0用不了，有声音没图像

### ISSUE THREAD

**Issue by qbundp** [xiaoyaocz/dart_simple_live#74]
新发布的1.2.0，arm64-v8a版用不了，有声音，但加载不出图像，换源也不换不了...

**Comment by qbundp** [comment]
希望能增加个《关注的导出》功能，免得出问题清除数据后又得一个个重新搜索关注...

**Comment by xiaoyaocz** [comment]
ios还是安卓，安卓的话尝试打开播放设置里的兼容模式

**Comment by qbundp** [comment]
安卓的，《兼容默认》好像是默认打开的，我再去看看

**Comment by qbundp** [comment]
谢谢，打开兼容模式后可以看了。希望后续版本能增加个《关注用户》的批量取关，以及导出与导入功能...
很好的APP，再次感谢！！
