### ISSUE TITLE
增加平台排序功能

### ISSUE THREAD

**Issue by kriovo** [xiaoyaocz/dart_simple_live#76]
1.是否可以修复后台播放 1.1.1可以 更新后就不可以
2.是否可以增加直播平台自定义排序

**Comment by xiaoyaocz** [comment]
我就没开发过后台播放啊😂
后续加上

**Comment by carlo0505** [comment]
> 我就没开发过后台播放啊😂 后续加上

直播息屏听直播几分钟后就会停止继续播放了，大佬是bug么
