### ISSUE TITLE
[BUG]拖动音量画面卡顿

### ISSUE THREAD

**Issue by zuu4297** [xiaoyaocz/dart_simple_live#92]
**拖动音量导致画面卡顿**
1.2.1的版本没这个问题了 刚刚更新1.2.2的版本又出现了拖动音量画面卡顿的情况
反馈前请确认下是否存在相似的Issues！！！

**重现步骤**
请在此输入重现步骤
1. xxx
2. xxx
3. xxx

**截图或视频**
https://github.com/xiaoyaocz/dart_simple_live/assets/127479732/f10173dc-ab8d-47f4-ae7a-8321134e87cd

**平台信息**
 - 设备: [e.g. 小米12]
 - 系统版本: [e.g. MIUI 14.07, Android 13.0]
 - APP版本: [e.g. 1.2.2]

**Comment by zuu4297** [comment]
1.24版本仍未修复。

**Comment by xiaoyaocz** [comment]
1.3.3问题是否还存在

**Comment by zuu4297** [comment]
> 1.3.3问题是否还存在

1.4.1 问题仍存在
