### ISSUE TITLE
鸿蒙4无法安装，纯净模式已关闭，提示没有证书[BUG]

### ISSUE THREAD

**Issue by sy4253** [xiaoyaocz/dart_simple_live#96]
**BUG内容**
输入BUG详细内容
反馈前请确认下是否存在相似的Issues！！！
![Screenshot_20230808_203436_com android packageinstaller](https://github.com/xiaoyaocz/dart_simple_live/assets/68688502/b74a34a2-58dc-4b8c-b3f4-1bba45c1f93e)

**平台信息**
 - 设备: [华为matepadpro11]
 - 系统版本: [鸿蒙4.0.0.108]
 - APP版本: [1.2.2]

**Comment by xiaoyaocz** [comment]
试试 https://zhidao.baidu.com/question/1869386436063490067.html

**Comment by sy4253** [comment]
鸿蒙4没找到关闭外部应用程序检查的开关，手机平板都试过了都找不到

**Comment by xiaoyaocz** [comment]
试试这个文件能不能安装 https://xiaoyaocz.lanzouy.com/i1LBl14uwena

**Comment by sy4253** [comment]
可以安装，感谢
