### ISSUE TITLE
小米手机报有木马病毒[BUG][BUG]

### ISSUE THREAD

**Issue by stan1943** [xiaoyaocz/dart_simple_live#97]
**BUG内容**
输入BUG详细内容
反馈前请确认下是否存在相似的Issues！！！

**重现步骤**
请在此输入重现步骤
1.小米手机报有木马病毒[BUG]

**截图或视频**
在这里贴上截图或视频
![Screenshot_2023-08-08-20-53-20-690_com xiaomi market](https://github.com/xiaoyaocz/dart_simple_live/assets/4471684/5c1cc61c-5762-4c84-aeba-8e5595fcf159)

**平台信息**
 - 设备: 红米k50u
 - 系统版本: MIUI14
 - APP版本: [e.g. 22]

**Comment by xiaoyaocz** [comment]
不知道小米抽啥风，无法解决。如不放心可自行打包
